Catrobat/Catty

src/Catty/DataModel/Scene/Scene.m
src/Catty/DataModel/Scripts/Script.m
src/Catty/Helpers/SensorHelper/SensorHandler.m

minor changes to get rid of compiler errors and warnings when having NSDebug uncommented

fixes #429

---

src/Catty/Extension&Delegate&Protocol/Protocols/BrickProtocol.h
src/Catty/FormulaEditor/InternFormulaParser.h
src/Catty/FormulaEditor/InternFormulaParser.m
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m

display name of object variable in ScriptCollectionView

---

src/Catty/DataModel/Program/Program.m
src/Catty/Extension&Delegate&Protocol/Extensions/Program+Extension/Program+CustomExtensions.h
src/Catty/Extension&Delegate&Protocol/Extensions/Program+Extension/Program+CustomExtensions.m
src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m
src/Catty/ViewController/Download/ProgramDetailStoreViewController.m
src/Catty/ViewController/Scene/ScenePresenterViewController.m
src/Catty/Views/Custom/CatrobatAlertView/CatrobatAlertView.h
src/Catty/Views/Custom/CatrobatAlertView/CatrobatAlertView.m

Fixes several memory issues

---

src/Catty/Extension&Delegate&Protocol/Extensions/GDataXMLElement/GDataXMLElement+CustomExtensions.m
src/Catty/Parser&Serialializer/NEW/XMLHandler/Bricks/MotionBricks/PointToBrick+CBXMLHandler.m
src/Catty/Parser&Serialializer/NEW/XMLHandler/VariablesContainer/VariablesContainer+CBXMLHandler.m

Remove compiler warnings for Release Build

---

src/CattyTests/ClearGrafficEffectBrickTests.m

fixes tests for iPhone 4S/5

---

src/Catty/Parser&Serialializer/NEW/XMLHandler/Bricks/MotionBricks/PointToBrick+CBXMLHandler.m
src/CattyTests/Parser & Serialization/CatrobatLanguage0.93/XMLSerializerTests/Unit Tests/XMLSerializerTests.m

removed pointedObject validation

---

src/CattyTests/ComeToFrontBrickTests.m

all tests passed

---

src/Catty/Parser&Serialializer/NEW/XMLHandler/VariablesContainer/VariablesContainer+CBXMLHandler.m

do not serialise object variables for invalid objects

---

src/precompile-tests.swift

add year check to license header tests + additional check for Readme.md

Optimize precompile scripts

---

.gitignore
src/Catty.xcodeproj/project.pbxproj
src/CattyTests/CattyTests-Info.plist
src/iOS_Lang/en.lproj/Localizable.strings
src/precompile-tests.swift

- fixes precompile.swift script
- changes deployment target to iOS8.3 (released a few hours ago ;))

IOS-41 #Done

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m

refactored delete Look and save painted image delegates

---

src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/Helpers/Util/Util.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

IOS-59 IOS-60 IOS-61 IOS-62 IOS-65 IOS-68 #done

IOS 59 60 61 62

---

src/Catty/DataModel/Bricks/SensorBricks/LedOffBrick.m
src/Catty/DataModel/Bricks/SensorBricks/LedOnBrick.m
src/Catty/DataModel/Bricks/SensorBricks/VibrationBrick.m

IOS-70 #done

---

src/Catty/DataModel/Bricks/SensorBricks/VibrationBrick.m

performSelector:withObject:afterDelay: is not calling vibe: when not
run on main queue.

IOS-74 #done

---

src/Catty/DataModel/BrickManager/BrickManager.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryViewController.h
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickSelectionViewController.h

IOS-77 #done

---

src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Helpers/Util/Util.m
src/iOS_Lang/en.lproj/Localizable.strings

IOS-78 #done

---

src/Catty/Extension&Delegate&Protocol/Protocols/Bricks/BrickCellFragmentProtocol.h
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellFragments/BrickCellLookFragment.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellFragments/BrickCellMessageFragment.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellFragments/BrickCellObjectFragment.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellFragments/BrickCellSoundFragment.m

IOS-80 #done

---

src/Catty/DataModel/Scene/Scene.m
src/Catty/Extension&Delegate&Protocol/Extensions/UIImage+Extension/UIImage+CatrobatUIImageExtensions.m

IOS-92 #done

---

src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.h
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellFormulaData.m

force change formula bug fix (double touch)

IOS-82 #done

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

do not cancel touches in view for InteractivePopGestureRecognizer

IOS-97 #done

---

src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m

disabled ABC button in formula editor for all bricks excluding speakbrick
did grey out manually because setEnabled NO didn't do it for me

IOS-15 #done

---

src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m

Now you can enter Strings again in the formula Editor

fixed alertView for ABC entry

---

src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/ViewController/Scene/ScenePresenterViewController.m
src/iOS_Lang/en.lproj/Localizable.strings

Changed title of icon in the sidebar from “Grid” to “Axes”.

IOS-118 #done

---

src/Catty/DataModel/Bricks/MoveBricks/MoveNStepsBrick.m
src/Catty/DataModel/Bricks/RotationBricks/PointInDirectionBrick.m
src/Catty/DataModel/Bricks/RotationBricks/TurnLeftBrick.m
src/Catty/DataModel/Bricks/RotationBricks/TurnRightBrick.m
src/Catty/DataModel/Bricks/SoundBricks/ChangeVolumeByNBrick.m
src/Catty/DataModel/Bricks/SoundBricks/SetVolumeToBrick.m

default values are integers instead of floats now

IOS-126 #done

---

src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Programs/MyProgramsViewController.m

Changed insets of separator lines in CatrobatTableViewController and
MyProgramsViewContoller to zero -> continuous lines.

IOS-138 #done

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

I can’t reproduce this given crash anymore!

IOS-129 #done

---

src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/PocketPaint/PaintViewController.m
src/iOS_Lang/de.lproj/Localizable.strings

IOS-142 #done

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/Views/Custom/CollectionViewCells/BrickCell.m

set animation time to from 0.4 to 0.8, don't know what slower exactly means

IOS-109 #done

---

src/Catty/App-Info.plist
src/Catty/PocketPaint/YKImageCropperView.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

added sort function to delete (if you delete bricks top down there could be an index error in case of different brick sizes)
fixed formal error in auto cropping

IOS-121 #done

---

src/Catty/App-Info.plist
src/Catty/Helpers/Util/Util.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

We can talk about the alpha values with the usability team, but I think
these values fit quite good.

IOS-110 #done

---

src/Catty/FormulaEditor/InternFormulaKeyboardAdapter.m
src/Catty/Storyboard+XIB/FormulaEditor.xib

Changed „FunctionWithoutParametersAndBrackets“ to correct one using two
parameters.

IOS-152 #done

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickSelectionViewController.m

Changed BarButtonItem according to UX-Team from right and „Done“ to
left and „Cancel“.

IOS-135 #done

---

src/Catty/Defines/UIDefines.h
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/PocketPaint/PaintViewController.m
src/Catty/PocketPaint/ResizeViewManager.m
src/Catty/ViewController/BaseViewController/BaseTableViewController.m
src/Catty/ViewController/BaseViewController/BaseWebViewController.m

Added response when user saves image to camera roll and tidied up
parameters (put hardcoded values to UIDefines to keep consistency and
maintainability).

IOS-156 #done

---

src/Catty/Storyboard+XIB/iPhone.storyboard
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m

Always keep aspect ratio and centered continue button.

IOS-174 #done

---

src/Catty/App-Info.plist
src/Catty/ViewController/CatrobatTableViewController/InfoPopupViewController.m

removed build number since already displayed in debug alert

IOS-149 #done

---

src/Catty/Storyboard+XIB/LaunchScreen.storyboard

Adaptive Font Size and Autolayout to adapt on small screens.

IOS-176 #done

---

src/Catty/App-Info.plist
src/Catty/DataModel/UserVariable/UserVariable.m

Changed "mutableCopy" to "copy" since NSNumber is immutable.

IOS-160 #done

---

src/Catty/ViewController/Download/SearchStoreViewController.m

Added possibility to hide keyboard by tapping outside the keyboard and
hide (now redundant) cancel button on small devices.

IOS-178 #done

---

src/Catty/App-Info.plist
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickManager/BrickInsertManager.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/Views/3rdParty/LXReorderableCollectionViewFlowLayout/LXReorderableCollectionViewFlowLayout.m

also removed the animation part

IOS-189 #done

---

src/Catty/App-Info.plist
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.h
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m

Revert "Ios 128"

---

src/Catty/App-Info.plist
src/Catty/Extension&Delegate&Protocol/Extensions/UIColor+Extension/UIColor+CatrobatUIColorExtensions.h
src/Catty/Extension&Delegate&Protocol/Extensions/UIColor+Extension/UIColor+CatrobatUIColorExtensions.m
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellFormulaData.m

Revert "Color improvements"

---

src/Catty/App-Info.plist
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickManager/BrickInsertManager.h
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickManager/BrickInsertManager.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickManager/BrickMoveManager.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/Views/3rdParty/LXReorderableCollectionViewFlowLayout/LXReorderableCollectionViewFlowLayout.m

IOS 218 #done
+  refactoring of BrickMove Manager class

IOS 218 #done

---

src/Catty.xcodeproj/project.pbxproj
src/Catty.xcodeproj/xcshareddata/xcschemes/Catty (RELEASE).xcscheme
src/Catty/App-Info.plist

Removed test-targets from release-build scheme.

IOS-259 #done

---

src/Catty UITests/Protocol/UITestProtocol.swift
src/Catty UITests/SoundsTVCTests.swift
src/Catty.xcodeproj/project.pbxproj
src/Catty/App-Info.plist

IOS-254 #done

---

src/Catty UITests/LooksTVCTests.swift
src/Catty UITests/Protocol/UITestProtocol.swift
src/Catty.xcodeproj/project.pbxproj
src/Catty/App-Info.plist

IOS-255 #done

---

src/Catty UITests/ObjectTVCTests.swift
src/Catty.xcodeproj/project.pbxproj

IOS-252 #done

---

src/Catty UITests/CatrobatTVCTests.swift
src/Catty.xcodeproj/project.pbxproj

Added UI-Tests for CatrobatTVC.

IOS-253 #done

---

src/Catty UITests/LooksTVCTests.swift
src/Catty UITests/Protocol/UITestProtocol.swift

Fixed UI-Testcases in LooksTVCTests.

IOS-279 #done

---

src/Catty UITests/CatrobatTVCTests.swift
src/Catty UITests/LooksTVCTests.swift
src/Catty UITests/MyProgramsVCTests.swift
src/Catty UITests/ObjectTVCTests.swift
src/Catty UITests/ProgramTVCTests.swift
src/Catty UITests/Protocol/UITestProtocol.swift
src/Catty UITests/SoundsTVCTests.swift

Added method to UITestProtocol to skip welcome screen if it is shown
and call it in setUp phase.

IOS-283 #done

---

src/Catty/App-Info.plist
src/Catty/Defines/UIDefines.h
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Phiro/PhiroMotorMoveBackwardBrick+CBXMLHandler.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Phiro/PhiroMotorMoveForwardBrick+CBXMLHandler.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Phiro/PhiroMotorStopBrick+CBXMLHandler.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Phiro/PhiroPlayToneBrick+CBXMLHandler.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Phiro/PhiroRGBLightBrick+CBXMLHandler.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/ViewController/Continue&New/ProgramTableViewController.m
src/Catty/ViewController/Programs/DescriptionPopopViewController.m
src/Catty/ViewController/Programs/MyProgramsViewController.m

IOS-271 #done
IOS-272 #done
IOS-269 #done
IOS-280 #done
IOS-250 #done

Marc fixes

---

src/Catty/Helpers/Logger/LoggerProperties.plist

Removed GDataXMLElement debug output using LoggerProperties.plist
blacklist.

IOS-286 #done

---

src/Catty/App-Info.plist
src/Catty/AppDelegate.m
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Helpers/FileManager/FileManager.h
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.h
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/iOS_Lang/en.lproj/Localizable.strings

Added possibility to open *.catrobat files from third-party apps (e.g.
from Safari, Dropbox, etc.).

IOS-249 #done

---

src/Catty/App-Info.plist
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Helpers/ResourceHelper/ResourceHelper.m
src/Catty/ViewController/BaseViewController/BaseCollectionViewController.m
src/Catty/ViewController/BaseViewController/BaseTableViewController.m
src/iOS_Lang/en.lproj/Localizable.strings

This PR checks if BLE is available and turned on before opening the connection VC

alerts at connection if bluetooth is available

---

src/Catty/App-Info.plist
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Helpers/Bluetooth/BluetoothService.swift
src/Catty/Helpers/Firmata/Firmata.swift
src/Catty/ViewController/BluetoothDeviceSelection/BluetoothDevicesTableViewController.swift
src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.m
src/iOS_Lang/en.lproj/Localizable.strings

delete known  devices
code refactoring

Bluetooth addons

---

src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/ViewController/Scene/ScenePresenterViewController.m
src/iOS_Lang/en.lproj/Localizable.strings

Change label to „stop“ when recording and to „recording“ after stopped.

IOS-336 #done

---

src/Catty/App-Info.plist
src/Catty/PocketPaint/UIImage+FloodFill.m

Fill Tool works now
removed all the castings for byteIndex -> gives wrong koordinates

IOS-314 #done

---

src/Catty UITests/CatrobatTVCTests.swift
src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/iOS_Lang/en.lproj/Localizable.strings
src/synchronize_localization.py

Working for all cases except UI-Tests (not possible as this runs in an
own process).

IOS-281 #done

---

src/Catty/App-Info.plist
src/Catty/Defines/UIDefines.h
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m

- Computed String shown in notification 
- We can discuss about the duration length -> 2.0 sec in this implementation

IOS-355 #done

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/App-Info.plist
src/Catty/Helpers/Util/SwiftBridge.swift
src/Podfile

Fixed issue occurring after updating siren, i.e. removed setting of
appID.

IOS-384 #done

---

src/Catty/ViewController/MediaLibraryViewController.m

added URL encoding for image and sound name -> replace "+" by " " and replace %-tags

IOS-389 #done decoded URL

---

src/CattyTests/PlayerEngine/CBBackendTests.swift

IOS 294 done

---

src/Catty/PocketPaint/Tools/MirrorRotationZoomTool.m
src/Catty/PocketPaint/ViewController/PaintViewController.m

Added an image context to get the mirrored or rotated image and save it to the saveImage.

#IOS-421 fixed mirror tool

---

src/Catty/AppDelegate.m

added resumeAction call in applicationDidBecomeActive

IOS-424 done

---

src/Catty/Storyboard+XIB/iPhone.storyboard

program names get shortened now

IOS-426 updated constraints for UILabel

---

src/Catty/ViewController/Scene/ScenePresenterViewController.m

moved pauseAction and stopProgramAction to a background queue

IOS-396 done

---

src/Catty/Helpers/Util/TableUtil.m
src/Catty/ViewController/Download/FeaturedProgramsStoreViewController.m

To simulate a slow internet connection, use Apple's 'Network Link Conditioner'

IOS-377 Changed the size of preview images in FeaturedProgramsStoreViewController

---

src/Catty/ViewController/Download/FeaturedProgramsStoreViewController.m

Added manually whack a mole and galaxy war.

Featured Programs

---

src/Catty/DataModel/Formula/FormulaElement.m
src/Catty/DataModel/UserVariable/UserVariable.h
src/Catty/DataModel/VariablesContainer/VariablesContainer.h
src/Catty/DataModel/VariablesContainer/VariablesContainer.m
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.h
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Program/Program+CBXMLHandler.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/iOS_Lang/en.lproj/Localizable.strings

Lists can now be instantiated. They are the same as a variable, but with a "isList" flag set to true and an Array as value.
In the Formula editor, Lists can now be created. Due to the missing parser and serializer functionality for lists, they are still saved as normal variables though and therefore appear in the variables section after restart.

IOS-467 Lists can now be instantiated

---

src/Catty/Defines/NetworkDefines.h
src/Catty/ViewController/Download/FeaturedProgramsStoreViewController.m
src/Catty/ViewController/Download/RecentProgramsStoreViewController.m
src/Catty/ViewController/Download/SearchStoreViewController.m
src/CattyTests/Download/FeaturedProgramsStoreViewControllerTests.m
src/CattyTests/Download/RecentProgramsStoreViewControllerTests.m
src/CattyTests/Download/SearchStoreViewControllerTests.m

max_version works for the API calls mentioned in JIRA and also for mostViewed.json, which I therefore also added

IOS 464 Add max_version parameter to API calls

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

Only merge if UX team approves the disabling of swipe back gesture in script overview

IOS-447 Move Bricks and Scripts

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickManager/BrickMoveManager.m
src/CattyTests/Bricks/BrickMoveManager/Abstract/BrickMoveManagerAbstractTest.h
src/CattyTests/Bricks/BrickMoveManager/Abstract/BrickMoveManagerAbstractTest.m
src/CattyTests/Bricks/BrickMoveManager/BrickMoveManagerForeverTests.m
src/CattyTests/Bricks/BrickMoveManager/BrickMoveManagerLogicTests.m
src/CattyTests/Bricks/BrickMoveManager/BrickMoveManagerRepeatTests.m

Nested bricks cannot be moved to another empty script anymore, tests included

IOS-475 Moving nested Bricks

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m
src/Catty/PocketPaint/ViewController/PaintViewController.h
src/Catty/PocketPaint/ViewController/PaintViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController.m
src/Catty/ViewController/Continue&New/ProgramTableViewController.m
src/Catty/ViewController/Programs/MyProgramsViewController.m
src/Catty/Views/Custom/AlertController/AlertController.swift
src/Catty/Views/Custom/AlertController/AlertControllerBuilder.swift
src/Catty/Views/Custom/AlertController/BaseAlertController.swift
src/Catty/Views/Custom/CatrobatAlertController/CatrobatAlertController.h
src/Catty/Views/Custom/CatrobatAlertController/CatrobatAlertController.m

First part of [IOS 470](https://github.com/Catrobat/Catty/pull/869)

IOS 482 Refactor Action Sheets

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/Helpers/ResourceHelper/ResourceHelper.h
src/Catty/Helpers/ResourceHelper/ResourceHelper.m
src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m
src/Catty/PocketPaint/ViewController/PaintViewController.h
src/Catty/PocketPaint/ViewController/PaintViewController.m
src/Catty/ViewController/BaseViewController/BaseCollectionViewController.h
src/Catty/ViewController/BaseViewController/BaseCollectionViewController.m
src/Catty/ViewController/BaseViewController/BaseTableViewController.h
src/Catty/ViewController/BaseViewController/BaseTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LookImageViewController.h
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LookImageViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController.m
src/Catty/ViewController/Continue&New/ProgramTableViewController.m
src/Catty/ViewController/Programs/MyProgramsViewController.m
src/Catty/ViewController/Scene/ScenePresenterViewController.m
src/Catty/Views/Custom/AlertController/AlertController.swift
src/Catty/Views/Custom/AlertController/AlertControllerBuilder.swift
src/Catty/Views/Custom/AlertController/BaseAlertController.swift
src/Catty/Views/Custom/CatrobatAlertController/CatrobatAlertController.h
src/Catty/Views/Custom/CatrobatAlertController/CatrobatAlertController.m

Contains and depends on https://github.com/Catrobat/Catty/pull/887. 
Should be merged after https://github.com/Catrobat/Catty/pull/887 gets merged

IOS 483 Refactor Alert Views

---

src/Catty/DataModel/Formula/FormulaElement.m
src/Catty/DataModel/FormulaEditor/Functions.h
src/Catty/DataModel/FormulaEditor/Functions.m
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/FormulaEditor/InternFormulaKeyboardAdapter.m
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/Helpers/SensorHelper/SensorManager.h
src/Catty/Helpers/SensorHelper/TouchHandler.h
src/Catty/Helpers/SensorHelper/TouchHandler.m
src/Catty/PlayerEngine/Helper/CBSceneHelper.swift
src/Catty/Storyboard+XIB/FormulaEditor.xib
src/Catty/ViewController/Scene/ScenePresenterViewController.m
src/iOS_Lang/en.lproj/Localizable.strings

Added all required functions for IOS-512, along with a fix for the inaccurate coordinates being displayed for differently sized scenes.

[IOS-512] Functions for screen touch detection

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Catty-Bridging-Header.h
src/Catty/DataModel/Bricks/Look/SayBubbleBrick.h
src/Catty/DataModel/Bricks/Look/SayBubbleBrick.m
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Defines/UIDefines.h
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SayBubbleBrick+CBXMLHandler.h
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SayBubbleBrick+CBXMLHandler.m
src/Catty/PlayerEngine/Instructions/Look/SetSizeToBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Motion/ChangeSizeByNBrick+Instruction.swift
src/Catty/SayBubbleBrick+Instruction.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/BrickCell.m
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SayBubbleBrickCell.h
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SayBubbleBrickCell.m
src/iOS_Lang/en.lproj/Localizable.strings

[IOS-497] SayBubbleBrick

---

src/Catty/PocketPaint/Helper/ImagePicker.m

Tint color of navigation bar was not set

IOS-523 Paint: Choose image from Photo Library

---

src/Catty/App-Info.plist

A new build has been deployed to TestFlight

Increase build number

---

src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m

In the Formula Editor, now the inclination buttons are displayed before the acceleration ones.

Added inclination before acceleration

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

Remove code that calculated a wrong height for bricks located after a "When..." brick

IOS-532 Remove code that calculated a wrong height 

---

src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryViewController.m
src/Catty/Views/Custom/ViewControllerTransitions/BrickTransition.m

hotfix margins in Formula Editor supporting iOS 9 - 11 
also supporting iPhone X with safe Areas

[IOS-559-hotfix] Wrong margins in Formula Editor

---

src/Catty/Storyboard+XIB/FormulaEditor.xib
src/Catty/Storyboard+XIB/SceneMenuView.xib

IOS-550 add SafeAreas for FormulaEditor and SceneMenuView

---

src/Catty/ViewController/Scene/ScenePresenterViewController+Resources.swift

IOS-693 do not push scenepresenterviewcontroller twice

---

src/Catty/Defines/UIDefines.h
src/Catty/ViewController/Scene/ScenePresenterViewController.m

changed the delay of the animation for the menuView so it's longer visible

CATTY-119 changed delay of animation for menuView in running project

---

src/Catty UITests/VariablesTests.swift

*Please enter a short describtion of your pull request and add a reference to the Jira ticket.*
- [ x] Include the name of the Jira ticket in the PR’s title
- [ x] Include a summary of the changes plus the relevant context
- [ x] Choose the proper base branch (*develop*)
- [ x] Confirm that the changes follow the project’s coding guidelines
- [ x] Verify that the changes generate no compiler or linter warnings
- [ x] Perform a self-review of the changes
- [ x] Verify to commit no other files than the intentionally changed ones
- [ x] Confirm that new and existing unit tests pass locally
- [ x] Check that the …

Catty-129 Replace static strings with defines in VariablesTests

---

src/Catty UITests/Defines/LanguageTranslationDefinesUI.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings

Add a dummy translation to test GitHub action after merge. This translation will be removed in a separate PR again.

CATTY-148 Add translation to test GitHub action

---

src/Catty UITests/Defines/LanguageTranslationDefinesUI.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/fastlane/Fastfile

Add a dummy translation to test GitHub action after merge. This translation will be removed in a separate PR again.

CATTY-148 Add another translation to test GitHub action

---

.github/workflows/scheduled-upload-crowdin.yml
src/fastlane/Fastfile

Remove PR trigger and setup a scheduled event which triggers on the develop branch on midnight every day. For further details see ticket description.

CATTY-148 Remove PR trigger and setup scheduled event

---

.github/workflows/scheduled-upload-crowdin.yml

Change branch for GitHub workflow to 'develop'.

CATTY-148 Change branch for GitHub workflow

---

src/Catty UITests/Defines/LanguageTranslationDefinesUI.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings

Remove dummy translation for GitHub action.

CATTY-148 Remove translation for GitHub action

---

.github/workflows/scheduled-upload-crowdin.yml

Change schedule to everyday midnight.

CATTY-148 Change schedule to everyday midnight

---

.github/workflows/scheduled-upload-crowdin.yml
src/fastlane/Fastfile

Only update fastlane if `FASTLANE_SKIP_UPDATE_CHECK` environment variable is not set.

CATTY-148 Set environment variable for GitHub action

---

.github/pull_request_template.md

*Please enter a short describtion of your pull request and add a reference to the Jira ticket.*

CATTY-146 Correct typo

---

.github/pull_request_template.md

Update Slack channel name

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/ViewController/Upload/LoginViewController.m
src/CattyTests/CattyTests-Bridging-Header.h
src/CattyTests/Mocks/LoginViewControllerMock.swift
src/CattyTests/Utils/LoginViewControllerTests.swift

Improved Feedback when no answer is available on Login Action.
Added Unit Tests for handleLoginWithResponse.

Catty-52 Improved Feedback when no answer is available on Login

---

src/Catty UITests/Defines/LanguageTranslationDefinesUI.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.m

Add a description for the Arduino extension in the settings screen

CATTY-128 add description for arduino extension

---

src/Catty.xcodeproj/project.pbxproj

Remove the "Run Script Phase"called "Remove git hooks".

CATTY-158 Remove Run Script Phase

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/ViewController/CatrobatTableViewController/AboutPocketCodeOptionTableViewController.h
src/Catty/ViewController/CatrobatTableViewController/AboutPocketCodeOptionTableViewController.m
src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.m

Add easer egg for Firebase Crashlytics (to be removed later again). For more details see Jira ticket.

CATTY-161 Add easer egg for Firebase Crashlytics

---

src/Catty/Supporting Files/Firebase/GoogleService-Info.plist

Use organizational Firebase account.

CATTY-167 Change Firebase account

---

src/Catty/App-Info.plist
src/Catty/Setup/Firebase/AppDelegateFirebaseExtension.swift
src/CattyTests/Setup/Firebase/FirebaseCrashlyticsSetupTests.swift

CATTY-171 Enable Firebase Analytics

---

src/Catty/AppDelegate.m
src/Catty/PocketPaint/Helper/ImagePicker.m
src/Catty/PocketPaint/ViewController/PaintViewController.m
src/Catty/ViewController/BluetoothDeviceSelection/BluetoothPopupVC.swift
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m

The cancel button is nearly invisible on image upload.

CATTY-181 Cancel button nearly invisible on image upload

---

src/Catty/Views/Custom/PlaceHolderView/PlaceHolderView.m

CATTY-127 Found solution for iphone6s where the text are too wide

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Settings.bundle/Root.plist
src/CattyTests/FileManager/CBFileManagerTests.swift

Changed version number in `App-Info.plist` and `Settings.bundle/Root.plist` to 0.6.12

CATTY-179 Wrong application version in settings

---

src/Catty UITests/ScriptCollectionView/BrickCellTests.swift
src/Catty/PocketPaint/ViewController/PaintViewController.m
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SetBackgroundBrickCell.m

After the necessary changes, SetBackgroundBrick now works as intended.

Catty-165: SetBackgroundBrick doesn't work

---

.github/workflows/swiftlint.yml

Contributors frequently do not have `SwiftLint` installed on their local development machines. Also, often log files are not scanned carefully, resulting in ignoring (unnoticed) Linter warnings when opening a pull request. Having the goal to improve code quality and to have a persistent code style, it is important to pay attention to those `SwiftLint` warnings.
To counteract this issue, a new GitHub Action needs to be introduced which
- checks changes in a newly opened pull request for `SwiftLint` warnings,
- annotates these potential style violations directly on GitHub in the _Files changed_ tab, and
- introduces a "failing check" in case of warnings which disallows the pull request to be merged
To review this pull request, have a look at my fork which is using the same _GitHub Action_ …

CATTY-212 Introduce GitHub Action for SwiftLint

---

src/Catty/PocketPaint/Tools/DrawTool.m

Catty 193 Unusual Draw-Tool Behavior

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/Parser & Serialization/CatrobatLanguage0.991/XMLParserTests/Unit Tests/XMLParserTests0991.swift
src/CattyTests/Resources/ParserTests/Custom/CommentedOut/SpeakBrickWithoutCommentedOut_0991.xml

New project `SpeakBrick_0991.xml` with `speakBrick` is added.
`testSpeakBrick` added in `XMLParserTests0991.swift` to test the `speakBrick` .

CATTY-220 Additional project for parser tests

---

src/Catty/Supporting Files/App-Info.plist

Catty-214: Change media license

---

src/CattyTests/Bricks/ChangeBrightnessByNBrickTests.swift
src/CattyTests/Bricks/ChangeColorByNBrickTests.swift
src/CattyTests/Bricks/ChangeSizeByNBrickTests.swift
src/CattyTests/Bricks/ChangeTransparencyByNBrickTests.swift
src/CattyTests/Bricks/ChangeVariableBrickTests.swift
src/CattyTests/Bricks/ChooseCameraBrickTests.swift
src/CattyTests/Bricks/ClearGraphicEffectBrickTests.swift
src/CattyTests/Bricks/ComeToFrontBrickTests.swift
src/CattyTests/Bricks/DeleteItemOfUserListBrickTests.swift

Added tests for mutable copy for various bricks.

Catty-204: Add tests for mutable copy (part 1)

---

src/Catty UITests/ScriptCollectionView/BrickCellPickerViewerTest.swift

Following tests are merged:
- testChangeVariableDone and testChangeVariableCancel
- testChangeControlDone and testChangeControlCancel
For testChangeVariable :
1. Test perform for three different bricks which are `SetVariable, ChangeVariable, ShowVariable`
2. Creating 3 new variables which are `testVariable1, testVariable2, testVariable3` common to all the three bricks.
3.  pickerView is opened, the first variable is selected and the done button is pressed. 
4. Checking if the selected variable is the first variable `VariableView_testVariable1` or not.
5. Again pickerView is opened, the third variable is selected and the cancel button is pressed.
6. Checking if the selected variable is the previous variable `VariableView_testVariable1` or not.
7. `3 to 6` is performed again for the …

CATTY-213 Merge UI tests for "Brick cell"

---

src/Catty.xcodeproj/project.pbxproj

Change bundle identifier for tests

CATTY-227 Change bundle identifier for tests

---

src/CattyTests/Bricks/GoNStepsBackBrickTests.swift
src/CattyTests/Bricks/HideBrickTests.swift
src/CattyTests/Bricks/HideTextBrickTests.swift
src/CattyTests/Bricks/IfOnEdgeBounceBrickTests.swift
src/CattyTests/Bricks/InsertItemIntoUserListBrickTests.swift
src/CattyTests/Bricks/MoveNStepsBrickTests.swift
src/CattyTests/Bricks/NextLookBrickTests.swift
src/CattyTests/Bricks/PlaceAtBrickTests.swift
src/CattyTests/Bricks/PointInDirectionBrickTests.swift

- GoNStepsBackBrick
- HideBrick
- HideTextBrick
- IfOnEdgeBounceBrick
- InsertItemIntoUserListBrick
- MoveNStepsBrick
- NextLookBrick
- PlaceAtBrick
- PointInDirectionBrick

CATTY-205 Add tests for mutable copy (part 2)

---

src/Catty/DataModel/UserVariable/UserVariable.h
src/Catty/DataModel/UserVariable/UserVariable.m
src/CattyTests/DataModel/VariablesContainerTest.swift

- allVariables
- allLists
- allVariablesAndLists
- objectVariablesForObject
- objectListsForObject

CATTY-230 Add tests for VariableContainer (part 1)

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Helpers/FileManager/CBFileManager.h
src/Catty/Storyboard+XIB/iPhone.storyboard
src/Catty/ViewController/Download/ProjectDetailStoreViewController.h
src/Catty/ViewController/Help/HelpWebViewController.swift
src/CattyTests/ViewController/HelpWebViewControllerTests.swift

Updated _UIWebView_ to _WKWebView_ in _HelpWebViewController.swift_ along with all delegates.

Catty-77: Migrate UIWebView to WKWebView

---

src/CattyTests/DataModel/VariablesContainerTest.swift

Added tests for the following methods:
- spriteObjectForObjectVariable
- isProjectVariableOrList
- removeObjectVariablesForSpriteObject
- removeObjectListsForSpriteObject

Catty-231: Added tests for VariablesContainer (part 2)

---

src/CattyTests/DataModel/VariablesContainerTest.swift

- isEqualToVariablesContainer
- mutableCopy

CATTY-235 Add tests for VariableContainer (part 5)

---

src/CattyTests/DataModel/VariablesContainerTest.swift

Added tests for the following methods:
- getUserVariableNamed
- getUserListNamed
- removeUserVariableNamed
- removeUserListNamed

Catty-232: Added tests for VariablesContainer (part 3)

---

src/CattyTests/DataModel/UserVariableTests.swift

CATTY-236 Add tests for UserVariable

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m
src/Catty/Parser&Serialializer/ProjectMigrator.swift
src/Catty/Parser&Serialializer/ProjectMigratorProtocol.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/CattyTests/FileManager/CBFileManagerMockTests.swift
src/CattyTests/Mocks/CBFileManagerMock.swift
src/CattyTests/Project/ProjectMigratorTest.swift
src/CattyTests/Utils/UtilTests.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

A `project migrator` service is introduced by the following:
- ProjectMigratorProtocol.swift
- ProjectMigrator.swift

CATTY-226 Implement project migrator

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Supporting Files/Catty-Bridging-Header.h
src/CattyTests/Views/Data/BrickCellVariableDataTests.swift

Added tests for BrickCellVariableData

Catty-239: Add tests for BrickCellVariableData

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/UserVariable/UserDataProtocol.swift
src/Catty/DataModel/UserVariable/UserVariable.swift

Created a new protocol called `UserDataProtocol` and implemented in `UserVariable` class

CATTY-245 Create UserData protocol

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/UserData/UserDataProtocol.swift
src/Catty/DataModel/UserData/UserList.swift
src/Catty/DataModel/UserData/UserVariable.swift
src/CattyTests/DataModel/UserListTest.swift

- Created a new class `UserList` (Catty/DataModel/UserData/)
- Moved the UserVariable and UserDataProtocol to this new folder
- Removed the empty Catty/DataModel/UserVariable folder
- Added a new test  for the new class `UserList`

CATTY-250 Create model for UserList

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/UserData/UserList.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLParserHelper.h
src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLParserHelper.m
src/CattyTests/Parser & Serialization/Helper/CBXMLParserHelperTests.swift

- Created `findUserListInArray` function
- Modified `findUserVariableInArray`  function

CATTY-266 Add additional method to parser helper

---

src/Catty/DataModel/UserData/UserVariable.swift
src/Catty/Parser&Serialializer/Old Parser/ProjectParser.m

Remove default initializer for UserVariable

CATTY-260 Remove default initializer for UserVariable

---

src/Catty/DataModel/VariablesContainer/VariablesContainer.h
src/Catty/DataModel/VariablesContainer/VariablesContainer.m
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserVariable/UserVariable+CBXMLHandler.m
src/CattyTests/DataModel/VariablesContainerTest.swift

Split function isProjectVariableOrList into flowwoing function:
- isProjectVariable
- isProjectList

CATTY-262 Split up isProjectVariableOrList method

---

README.md

For further details have a look at https://github.com/m-herold/Catty/tree/CATTY-265.

CATTY-265 Update links in README

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/Bricks/BrickUserDataTests.swift

- The `BrickWithUserVariableTests` name changed to `BrickUserDataTests`
- Added few new test to `BrickUserDataTests`

CATTY-290 Add additional tests to BrickWithUserVariableTests

---

src/Catty.xcodeproj/project.pbxproj
src/CattyUITests/ListTests.swift
src/CattyUITests/VariableTests.swift

CTTY-293 Add UI tests for lists

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/ProgramDefines.h
src/Catty/Defines/SpriteKitDefines.swift
src/Catty/Defines/UIDefines.h
src/Catty/Helpers/BrickHelpers/BubbleBrickHelper.swift
src/Catty/PlayerEngine/Instructions/Look/SayForBubbleBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/ThinkForBubbleBrick+Instruction.swift
src/Catty/PlayerEngine/Scene/CBScene.swift
src/CattyTests/Bricks/BubbleBrickTests.swift
src/CattyTests/SceneTests.swift

Catty-274: Create SpriteKitDefines

---

src/Catty/PlayerEngine/CBPlayerConfig.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
src/Catty/PlayerEngine/Protocols/CBSchedulerProtocol.swift
src/Catty/PlayerEngine/Scene/CBScene.swift
src/Catty/PlayerEngine/Scheduler/CBScheduler.swift
src/CattyTests/PlayerEngine/Mocks/CBSpriteNodeMock.swift
src/CattyTests/SceneTests.swift

- Override update method in CBScene, Implemented update method in CBSpriteNode
- Added tests for update method calls

Catty-272: Implement update function for SpriteNodes

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/VariablesContainer/VariablesContainer.h
src/Catty/DataModel/VariablesContainer/VariablesContainer.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/SpriteObject/SpriteObject+CBXMLHandler.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserVariable/UserVariable+CBXMLHandler.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/VariablesContainer/VariablesContainer+CBXMLHandler.m
src/CattyTests/DataModel/VariablesContainerTest.swift
src/CattyTests/Parser & Serialization/CatrobatLanguage0.991/XMLSerializerTests/BlackBox Tests/XMLSerializerBlackBoxTests.swift
src/CattyTests/Resources/ParserTests/Custom/Data/UserData_0991.xml

When a local object variable with the same name is used in several objects, then the serialization does not work properly. Reproduce by creating a project similar to that one:
- Background with local variable "name"
- Object 1 with local variable "name"
- Object 2 with local variable "name"

CATTY-282 Fix serialization of local variables with duplicate names

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Configuration/PenConfiguration.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift

CATTY-275 Implement PenConfiguration

---

src/Catty/PocketPaint/ColorPicker/NKOColorPickerView.m

CATTY-298 Fixed accidental dismiss/swipes in ColorPickerViewController

---

src/Catty/DataModel/Bricks/Arduino/ArduinoSendDigitalValueBrick.m
src/Catty/DataModel/Bricks/Data/DeleteItemOfUserListBrick.m
src/Catty/Extension&Delegate&Protocol/Protocols/Bricks/BrickData/BrickVariableProtocol.h
src/Catty/FormulaEditor/Helper/Brick+UserVariable.m
src/CattyTests/Bricks/BrickUserDataTests.swift

The Brick (UserVariable) extension is refactored.

CATTY-289 Refactor Brick extension for UserVariable and BrickVariableProtocol

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/SpriteKitDefines.swift
src/Catty/Extension&Delegate&Protocol/Extensions/SpriteNode/CBSpriteNodePenExtension.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
src/Catty/PlayerEngine/DataModel/LineShapeNode.swift
src/CattyTests/PlayerEngine/Mocks/CBSpriteNodeMock.swift
src/CattyTests/Scene/CBSpriteNodePenExtensionTests.swift
src/CattyTests/Scene/LineShapeNodeTests.swift
src/CattyTests/Scene/SceneTests.swift

- Implmented Pen feature for SpriteNode.
- Added tests for this new pen feature.

CATTY-276 Implement Pen feature for SpriteNode

---

src/Catty/PlayerEngine/Scene/CBScene.swift
src/CattyTests/Scene/SceneTests.swift

Implemented clearPenLines() method with tests

CATTY-280 Implement clear functionality for Pen

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Pen/PenDownBrick.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Defines/UIDefines.h
src/Catty/Extension&Delegate&Protocol/Extensions/UIColor+Extension/UIColor+CatrobatUIColorExtensions.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Pen/PenDownBrick+CBXMLHandler.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
src/Catty/PlayerEngine/Instructions/Pen/PenDownBrick+Instruction.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Pen/PenDownBrickCell.swift
src/CattyTests/Bricks/PenDownBrickTests.swift
src/CattyTests/Parser & Serialization/CatrobatLanguage0.991/XMLSerializerTests/Unit Tests/XMLSerializerTests.swift
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml
src/CattyTests/Scene/CBSpriteNodePenExtensionTests.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

- Implemented new BrickCategory: PenBrick
- Implemented PenDownBrick, its instruction and serialization with tests.
- Implemented PenBrickCell

CATTY-277 Implement PenDownBrick

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Array/SynchronizedArray.swift
src/CattyTests/DataModel/SynchronizedArrayTests.swift

Created a new class called `SynchronizedArray` for a thread-safe-array implementation.

CATTY-307 Create SynchronizedArray

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Pen/PenUpBrick.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Pen/PenUpBrick+CBXMLHandler.swift
src/Catty/PlayerEngine/Instructions/Pen/PenUpBrick+Instruction.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Pen/PenUpBrickCell.swift
src/CattyTests/Bricks/PenUpBrickTests.swift
src/CattyTests/Parser & Serialization/CatrobatLanguage0.991/XMLSerializerTests/Unit Tests/XMLSerializerTests.swift
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

- Implemented PenUpBrick, its instruction and serialization with tests.
- Implemented PenBrickCell

CATTY-278 Implement PenUpBrick

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Pen/PenClearBrick.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Pen/PenClearBrick+CBXMLHandler.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Pen/PenClearBrick+Instruction.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Pen/PenClearBrickCell.swift
src/CattyTests/Bricks/PenClearBrickTests.swift
src/CattyTests/Parser & Serialization/CatrobatLanguage0.991/XMLSerializerTests/Unit Tests/XMLSerializerTests.swift
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

- Implemented PenClearBrick, its instruction and serialization with tests.
- Implemented PenClearBrickCell

CATTY-279 Implement PenClearBrick

---

src/Catty/DataModel/UserData/UserDataProtocol.swift
src/Catty/DataModel/UserData/UserList.swift
src/Catty/Functions/List/ContainsFunction.swift
src/Catty/Functions/List/ElementFunction.swift
src/Catty/Functions/List/NumberOfItemsFunction.swift
src/Catty/PlayerEngine/Formula/FormulaManager+Interpreter.swift
src/CattyTests/Bricks/DeleteItemOfUserListBrickTests.swift
src/CattyTests/Bricks/InsertItemIntoUserListBrickTests.swift
src/CattyTests/Bricks/ReplaceItemInUserListBrickTests.swift
src/CattyTests/DataModel/UserListTest.swift
src/CattyTests/PlayerEngine/Functions/List/ContainsFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/List/ElementFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/List/NumberOfItemsFunctionTest.swift
src/CattyTests/UserListFunctionsTest.swift

Refactored `UserListProtocol` to make `value` property of UserList class as fileprivate.

CATTY-313 Refactor UserListProtocol

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/VariablesContainer/UserDataContainer.h
src/Catty/DataModel/VariablesContainer/UserDataContainer.m
src/Catty/Extension&Delegate&Protocol/Extensions/UserDataExtension.swift
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/PlayerEngine/Scene/CBScene.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/CattyTests/DataModel/UserDataContainerTest.swift
src/CattyTests/Project/ProjectTests.swift

Created a new swift extension for UserDataContainer.
Moved and converted the following function from UserDataContainer class to extension:
- (NSArray<UserVariable*>*)allVariables
- (NSArray<UserList*>*)allLists

CATTY-321 Add Swift extension for UserDataContainer

---

src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Pen/PenClearBrick+CBXMLHandler.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Scripts/Script+CBXMLHandler.m
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml

CATTY-325 Wrong serialization for PenClearBrick

---

src/Catty/DataModel/Bricks/Data/AddItemToUserListBrick.m
src/Catty/DataModel/Bricks/Data/ChangeVariableBrick.m
src/Catty/DataModel/Bricks/Data/DeleteItemOfUserListBrick.m
src/Catty/DataModel/Bricks/Data/HideTextBrick.m
src/Catty/DataModel/Bricks/Data/InsertItemIntoUserListBrick.m
src/Catty/DataModel/Bricks/Data/ReplaceItemInUserListBrick.m
src/Catty/DataModel/Bricks/Data/SetVariableBrick.m
src/Catty/DataModel/Bricks/Data/ShowTextBrick.m
src/Catty/DataModel/Project/Project.m
src/Catty/DataModel/VariablesContainer/UserDataContainer.h
src/Catty/DataModel/VariablesContainer/UserDataContainer.m
src/Catty/Extension&Delegate&Protocol/Extensions/UserDataExtension.swift
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellListData.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellVariableData.m
src/CattyTests/DataModel/UserDataContainerTest.swift
src/CattyTests/Parser & Serialization/CatrobatLanguage0.95/XMLParserTests/Unit Tests/XMLParserUserVariableTests095.swift
src/CattyTests/Project/ProjectTests.swift

Removed the following functions from UserDataContainer
- allVariablesForObject
- allListsForObject
- objectVariablesForObject
- objectListsForObject
Following functions have been added to UserDataContainer extension as the replacement of the above-mentioned function 
- objectAndProjectVariables
- objectAndProjectLists
- objectVariables
- objectLists

CATTY-323 Add methods to Swift extension for UserDataContainer

---

src/Catty/Views/Custom/CollectionViewCells/BrickCells/Control/LoopEndBrickCell.m

Catty - 303 Incorrect height for "End of (Repeat) Loop" Brick

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/SpriteObject/CBPosition.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
src/Catty/PlayerEngine/Instructions/Motion/ChangeYByNBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Motion/IfOnEdgeBounceBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Motion/MoveNStepsBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Motion/PlaceAtBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Motion/SetXBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Motion/SetYBrick+Instruction.swift
src/Catty/PlayerEngine/Sensors/Extensions/CBSpriteNode+Sensor.swift
src/CattyTests/Bricks/BubbleBrickTests.swift
src/CattyTests/Bricks/ClearGraphicEffectBrickTests.swift
src/CattyTests/Bricks/HideBrickTests.swift
src/CattyTests/Bricks/IfOnEdgeBounceBrickTests.swift
src/CattyTests/Bricks/MoveNStepsBrickTests.swift
src/CattyTests/Bricks/PlaceAtBrickTests.swift
src/CattyTests/Bricks/PointInDirectionBrickTests.swift
src/CattyTests/Bricks/SetXBrickTests.swift
src/CattyTests/Bricks/SetYBrickTests.swift
src/CattyTests/Bricks/ShowBrickTests.swift
src/CattyTests/PlayerEngine/CBSpriteNodeTests.swift

CATTY-353 Update catrobatPosition in CBSpriteNode atomically

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/Parser & Serialization/CatrobatLanguage0.93/BlackBox Tests/XMLParserBlackBoxTests093.swift
src/CattyTests/Resources/ParserTests/Custom/Data/UserVariables_093.xml
src/CattyTests/Resources/ParserTests/Custom/Data/UserVariables_0991.xml

Add an additional tests to XMLParserBlackBoxTests093 for the parsing of UserVariables which should compare the parsing of the old Parser (CBL 0.93) with the new Parser.

CATTY-362 Add additional XML for testing UserVariable parsing

---

src/Catty/Supporting Files/AppDelegate.swift
src/Catty/ViewController/Scene/ScenePresenterViewController.h
src/Catty/ViewController/Scene/ScenePresenterViewController.m
src/CattyTests/AppDelegateTests.swift
src/CattyTests/Mocks/ScenePresenterViewControllerSpy.swift

Do not resume project when paused

CATTY-367 Do not resume project when paused

---

src/Catty/DataModel/UserData/UserList.swift
src/Catty/Functions/Protocols/Function.swift
src/Catty/PlayerEngine/Formula/FormulaManager+Interpreter.swift
src/CattyTests/DataModel/UserListTest.swift

- Created new function `stringRepresentation` in UserList class .
- Moved the UserList logic from `interpretParameter` in the Function.swift to `stringRepresentation`.
- Used the same function i.e stringRepresentation in `interpretList` function of FormulaManager+Interpreter class.

Catty-366 Text representation of lists

---

src/Catty/PocketPaint/ViewController/PaintViewController.m

App crashes when drawing a new image in Paint and trying to save it to camera roll.

CATTY-381 Program closes unexpectedly when saving image to camera roll

---

src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift

CATTY-267 Delete the commented code

---

src/Catty/ViewController/Scene/ScenePresenterViewController+Resources.swift

CATTY-34: Project with Arduino Brick not starting

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Extension&Delegate&Protocol/Extensions/NSDataExtension.swift
src/Catty/PocketPaint/ViewController/PaintViewController.m
src/Catty/Settings.bundle/Root.plist
src/CattyTests/Extensions/NSDataExtensionTests.swift

Hotfix branch for version 0.6.15.

Hotfix 0.6.15

---

src/Catty/DataModel/Array/SynchronizedArray.swift
src/Catty/DataModel/Configuration/PenConfiguration.swift
src/Catty/Extension&Delegate&Protocol/Extensions/SpriteNode/CBSpriteNodePenExtension.swift
src/Catty/Extension&Delegate&Protocol/Extensions/SpriteNode/CBSpriteNodeSensorExtension.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
src/Catty/PlayerEngine/Instructions/Pen/PenClearBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Pen/PenDownBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Pen/PenUpBrick+Instruction.swift
src/CattyTests/Bricks/PenClearBrickTests.swift
src/CattyTests/Bricks/PenDownBrickTests.swift
src/CattyTests/Bricks/PenUpBrickTests.swift
src/CattyTests/DataModel/SynchronizedArrayTests.swift
src/CattyTests/Scene/CBSpriteNodePenExtensionTests.swift

CATTY-348 Invalid behaviour of pen with PlaceAt bricks

---

src/Catty/DataModel/Configuration/PenConfiguration.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
src/CattyTests/PlayerEngine/CBSpriteNodeTests.swift
src/CattyTests/Scene/PenConfigurationTests.swift

CATTY-368 Make PenSize dependent on screen ratio

---

src/Catty/Defines/SegueDefines.h

CATTY-271 delete unused segueDefines

---

src/CattyTests/FileManager/CBFileManagerTests.swift
src/CattyTests/Mocks/CBFileManagerMock.swift
src/CattyTests/Mocks/ProjectMock.swift
src/CattyTests/ViewController/ScriptCollectionViewControllerTests.swift

CATTY-399 Complete test run crashes because of faulty project

---

src/Catty/Defines/UIDefines.h
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Download/ChartProjects/ChartProjectCell.swift
src/Catty/ViewController/Download/SearchStore/SearchStoreCell.swift
src/Catty/ViewController/Projects/MyProjectsViewController.m

- Rounded borders applied to the project preview images in Store (Catrobat community) tabs and MyProjectsViewController.

CATTY-359 Add rounded borders for preview images

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/NetworkDefines.swift
src/Catty/Store/StoreProjectUploader.swift
src/Catty/ViewController/Upload/UploadViewController.swift
src/CattyTests/Mocks/StoreProjectUploaderMock.swift
src/CattyTests/Store/Upload/Fixture/StoreProjectUpload.fetchTags.invalidLanguageTag.json
src/CattyTests/Store/Upload/Fixture/StoreProjectUpload.fetchTags.success.json
src/CattyTests/Store/Upload/StoreProjectUploaderTests.swift

- Added new function fetchTags in StoreProjectUploaderProtocol
- Implemented fetchTags to fetch project tags forms share API

CATTY-393 Fetch project tags from API

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Pen/SetPenColorBrick.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Extension&Delegate&Protocol/Extensions/UIColorExtension.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Pen/SetPenColorBrick+CBXMLHandler.swift
src/Catty/PlayerEngine/Formula/FormulaManager+Interpreter.swift
src/Catty/PlayerEngine/Instructions/Pen/SetPenColorBrick+Instruction.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Pen/SetPenColorBrickCell.swift
src/CattyTests/Bricks/SetPenColorBrickTests.swift
src/CattyTests/Extensions/UIColorExtensionTests.swift
src/CattyTests/Parser & Serialization/CatrobatLanguage0.991/XMLSerializerTests/Unit Tests/XMLSerializerTests.swift
src/CattyTests/PlayerEngine/Formula/FormulaManagerInterpreterTests.swift
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

- Implemented SetPenColorBrick, its instructions and serialization with tests.
- Implemented SetPenColorBrickCell

CATTY-320 Implement SetPenColorBrick

---

src/Catty/PlayerEngine/Instructions/Look/SayForBubbleBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/ThinkForBubbleBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Motion/GlideToBrick+Instruction.swift
src/Catty/ViewController/Upload/UploadCategoryViewController.swift

-Bug fixed for wrong tag display when multiple tags already exist

CATTY-405 Project with multiple tags/categories only shows one tag at selection

---

src/CattyUITests/ObjectTVCTests.swift

Catty-406: testCopyObjectWithIfBricks.swift fail sometimes

---

src/Catty/Defines/NetworkDefines.swift
src/Catty/Storyboard+XIB/iPhone.storyboard
src/Catty/ViewController/Upload/UploadCategoryViewController.swift
src/Catty/ViewController/Upload/UploadViewController.swift
src/CattyTests/Mocks/StoreProjectUploaderMock.swift
src/CattyTests/ViewController/UploadCategoryViewControllerTests.swift
src/CattyTests/ViewController/UploadViewControllerTests.swift

- Removed hardcoded tags/categories
- Tags/categories are now fetched from API

CATTY-394 Use API to fetch project tags in UploadViewController

---

src/Catty/PlayerEngine/Instructions/IO/VibrationBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/SayForBubbleBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/ThinkForBubbleBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Motion/GlideToBrick+Instruction.swift
src/CattyTests/Bricks/VibrationBrickTests.swift

CATTY-397 : VibrationBrick with a number larger than INT-MAX crashes

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Pen/StampBrick.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Pen/StampBrick+CBXMLHandler.swift
src/Catty/PlayerEngine/Instructions/Pen/PenClearBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Pen/StampBrick+Instruction.swift
src/Catty/PlayerEngine/Stage/Stage.swift
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Pen/StampBrickCell.swift
src/CattyTests/Bricks/StampBrickTests.swift
src/CattyTests/Parser & Serialization/CatrobatLanguage0.991/XMLSerializerTests/Unit Tests/XMLSerializerTests.swift
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml
src/CattyTests/Scene/StageTests.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

- Implemented StampBrick, its instructions and serialization with tests.
- Implemented StampBrickCell
- Implemented a new method clearStampedSpriteNode in CBScene with tests

CATTY-352 Implement StampBrick

---

src/Catty/ViewController/Stage/StagePresenterViewController.h
src/Catty/ViewController/Stage/StagePresenterViewController.m
src/CattyTests/ViewController/Scene/StagePresenterViewControllerTest.swift

Changed grid view if the project is in landscape mode.

CATTY-402 Modify Grid View for Landscape Mode

---

src/Catty/ViewController/BaseViewController/BaseCollectionViewController.m
src/Catty/ViewController/BaseViewController/BaseTableViewController.m
src/Catty/ViewController/Stage/StagePresenterViewController.m

Change the orientation of the Scene (now "StagePresenter") depending on the chosen orientation of the project.
Also changed the hideMenu method of the scene as it would not disappear as a whole otherwise.

CATTY-335 Scene Presenter Landscape Mode

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLSerializerHelper.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SetBackgroundBrick+CBXMLHandler.m
src/Catty/Supporting Files/Catty-Bridging-Header.h
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellBackgroundData.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/BrickCell.m
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SetBackgroundBrickCell.m
src/CattyTests/Mocks/ScriptCollectionViewControllerMock.swift
src/CattyTests/Mocks/StoryboardMock.swift
src/CattyTests/Parser & Serialization/CatrobatLanguage0.991/XMLParserTests/Unit Tests/XMLParserTests0991.swift
src/CattyTests/Parser & Serialization/Helper/CBXMLSerializerHelperTests.swift
src/CattyTests/Resources/ParserTests/Custom/SetBackgroundBrick/SetBackgroundBrick_0991.xml
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml
src/CattyTests/ViewController/ScriptCollectionViewControllerTests.swift
src/CattyTests/Views/BrickCells/Data/BrickCellBackgroundDataTests.swift

Change Look selection and serialization for SetBackgroundBrick.

CATTY-411 Use Looks from Background for SetBackgroundBrick

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/ProjectDefines.h
src/Catty/Defines/ViewControllerDefines.h
src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController+Extensions.swift
src/Catty/Storyboard+XIB/iPhone.storyboard
src/Catty/Supporting Files/Catty-Bridging-Header.h
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/ViewController/Continue&New/SceneTableViewController.h
src/Catty/ViewController/Continue&New/SceneTableViewController.m
src/Catty/ViewController/Download/ProjectDetailStoreViewController.m
src/Catty/ViewController/Projects/MyProjectsViewController.m
src/Catty/ViewController/Projects/ProjectDescriptionViewController.swift
src/CattyTests/Extensions/UIViewControllerExtensionTests.swift

Renamed ProjectTableViewController to SceneTableViewController

CATTY-407 Rename ProjectTableViewController to SceneTableViewController

---

src/Catty/ViewController/Stage/ScenePresenterViewController+Screenshot.swift
src/Catty/ViewController/Stage/StagePresenterViewController.m
src/CattyTests/ViewController/Scene/StagePresenterViewControllerTest.swift

Now screenshots are taken on a per-scene level.

CATTY-409 Screenshots for Scenes

---

src/Catty/PlayerEngine/Stage/Stage.swift
src/CattyTests/Scene/StageTests.swift

CATTY-316 Show variable in the right position

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataStructures/JSON/StoreProject.swift
src/Catty/Extension&Delegate&Protocol/Extensions/CatrobatTableViewControllerExtension.swift
src/Catty/Pocket Code.entitlements
src/Catty/Storyboard+XIB/iPhone.storyboard
src/Catty/Supporting Files/AppDelegate.swift
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.h
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Download/ChartProjects/ChartProjectsStoreViewController.swift
src/Catty/ViewController/Download/FeaturedProjects/FeaturedProjectsStoreTableViewController.swift
src/Catty/ViewController/Download/SearchStore/SearchStoreViewController.swift
src/CattyTests/CatrobatTableViewControllerExtensionTests.swift
src/CattyTests/DataModel/StoreProjectTests.swift
src/CattyTests/Mocks/CatrobatTableViewControllerMock.swift
src/CattyTests/Mocks/StoreProjectDownloaderMock.swift

Due to changes in iOS, it was no longer possible to import projects from share.catrob.at
This PR implements apples newer [universal links] for importing projects
[universal links]: https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content

CATTY-101: Open project from URL

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Extension&Delegate&Protocol/Extensions/Notification/NotificationExtension.swift
src/Catty/Firebase/FirebaseAnalyticsReporter.swift
src/Catty/Firebase/FirebaseCrashlyticsReporter.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.h
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/CattyTests/Firebase/FirebaseAnalyticsTests.swift
src/CattyTests/Firebase/FirebaseCrashlyticsReporterTests.swift
src/CattyTests/Mocks/AnalyticsMock.swift
src/CattyTests/ViewController/ScriptCollectionViewControllerTests.swift

CATTY-371 "Brick removed" event for Firebase Analytics and Crashlytics

---

src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLParserHelper.m

Add support for landscapeMode on 32-bit systems

CATTY-417 Add support for landscapeMode on 32-bit systems

---

src/Catty/Defines/NetworkDefines.swift
src/Catty/ViewController/Help/HelpWebViewController.swift

Change URL for help page and remove alert

CATTY-422 CATTY-421 Change URL for help page and remove alert

---

src/Catty/Firebase/FirebaseAnalyticsReporter.swift
src/CattyTests/Firebase/FirebaseAnalyticsTests.swift
src/CattyTests/Firebase/FirebaseCrashlyticsReporterTests.swift

Log "Brick selected" event for Firebase Analytics & tests
CATTY-248 test brick parameter in firebase test methods

CATTY-248  firebase analytics add log for brick selected

---

src/Catty/BluetoothHelper/BluetoothHelper/Helper/String+Extensions.swift
src/Catty/BluetoothHelper/BluetoothHelper/Serialize:Deserialize/Data+Extensions.swift
src/Catty/BluetoothHelper/BluetoothHelper/Serialize:Deserialize/SerializerDeserializer.swift
src/Catty/FormulaEditor/InternFormulaParser.h
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/Helpers/Firmata/Firmata.swift
src/CattyTests/BluetoothDevices/Firmata/FirmataTests.swift
src/CattyTests/Extensions/UIImageExtensionTests.swift
src/CattyTests/Formula/FormulaElementTest.swift
src/CattyTests/Formula/FormulaParserErrorDetectionTest.m
src/CattyTests/Formula/FormulaParserFunctionsTest.m
src/CattyTests/Formula/FormulaParserOperatorsTest.m
src/CattyTests/Formula/FormulaParserTest.m
src/CattyTests/Formula/FormulaTest.swift

Removed compiler warnings, errors and introduce support for Xcode 11.7.

CATTY-192 Support for Xcode 11.7

---

src/Catty/Extension&Delegate&Protocol/Extensions/Notification/NotificationExtension.swift
src/Catty/Firebase/FirebaseAnalyticsReporter.swift
src/Catty/Firebase/FirebaseCrashlyticsReporter.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController+Disable.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/CattyTests/Firebase/FirebaseAnalyticsTests.swift
src/CattyTests/Firebase/FirebaseCrashlyticsReporterTests.swift
src/CattyTests/ViewController/ScriptCollectionViewControllerDisableTests.swift

Refactor disable Scripts and move the code into the "Disabled"-Extension. Add notifications for Firebase events.

CATTY-419 Refactor disable Scripts

---

src/Catty/ViewController/BaseViewController/BaseTableViewController.m

CATTY-423 Display error for object preview images after changing to portrait/landscape mode

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Look/AskBrick.swift
src/Catty/DataModel/UserData/UserVariable.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Defines/SpriteKitDefines.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/LookBricks/AskBrick+CBXMLHandler.swift
src/Catty/PlayerEngine/Instructions/Data/ChangeVariableBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Data/SetVariableBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Data/ShowTextBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/AskBrick+Instruction.swift
src/Catty/PlayerEngine/Stage/Stage.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/AskBrickCell.swift
src/CattyTests/Bricks/AskBrickTests.swift
src/CattyTests/CatrobatLanguage0.992/XMLParserTests/Unit Tests/XMLParserTests0992.swift
src/CattyTests/DataModel/UserVariableTests.swift
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0992.xml
src/CattyTests/Scene/StageTests.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

Implemented the AskBrick including some tests in swift.
This Brick prompts a user defined question. The answer is saved to a user variable.

CATTY-378 Implemented AskBrick

---

src/Cartfile
src/Cartfile.resolved
src/Catty.xcodeproj/project.pbxproj

upgraded the chrashlytics sdk via Carthage

CATTY-424 upgrade crashlytics sdk

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/Bricks/ArduinoSendDigitalValueBrickTests.swift
src/CattyTests/Bricks/ArduinoSendPWMValueBrickTests.swift
src/CattyTests/Bricks/ChangeBrightnessByNBrickTests.swift
src/CattyTests/Bricks/ChangeColorByNBrickTests.swift
src/CattyTests/Bricks/IfThenLogicBeginBrickTests.swift
src/CattyTests/Bricks/RepeatBrickTests.swift
src/CattyTests/Bricks/RepeatUntilBrickTests.swift
src/CattyTests/Bricks/WaitBrickTests.swift
src/CattyTests/Bricks/WaitUntilBrickTests.swift

Created new regression tests for the getFormulas method of the BrickFormulaProtocol. This is part 1 of 4, added test to following classes:
ArduinoSendDigitalValueBrickTests (new class)
ArduinoSendPWMValueBrickTests (new class)
IfLogicBeginBrickTests
IfThenLogicBeginBrickTests (new class)
RepeatBrickTests
RepeatUntilBrickTests
WaitBrickTests
WaitUntilBrickTests
ChangeBrightnessByNBrickTests
ChangeColorByNBrickTests

CATTY-284 Add tests for BrickFormulaProtocol

---

src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Scripts/Script+CBXMLHandler.m

Removed TODO comment in Script+CBXMLHandler

CATTY-431 Remove TODO comment in Script+CBXMLHandler

---

src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLParserHelper.m

Remove the outdated TODO comments from the CBXMLParserHelper.

CATTY-433 Remove TODO comments in CBXMLParserHelper

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/Bricks/AddItemToUserListBrickTests.swift
src/CattyTests/Bricks/ChangeVariableBrickTests.swift
src/CattyTests/Bricks/ChangeVolumeByNBrickTests.swift
src/CattyTests/Bricks/DeleteItemOfUserListBrickTests.swift
src/CattyTests/Bricks/InsertItemIntoUserListBrickTests.swift
src/CattyTests/Bricks/ReplaceItemInUserListBrickTests.swift
src/CattyTests/Bricks/SetVariableBrickTests.swift
src/CattyTests/Bricks/SetVolumeToBrickTests.swift
src/CattyTests/Bricks/SetXBrickTests.swift
src/CattyTests/Bricks/SetYBrickTests.swift
src/CattyTests/Bricks/ShowTextBrickTests.swift
src/CattyTests/Bricks/SpeakAndWaitBrickTests.swift
src/CattyTests/Bricks/SpeakBrickTests.swift
src/CattyTests/Bricks/TurnLeftBrickTests.swift
src/CattyTests/Bricks/TurnRightBrickTests.swift
src/CattyTests/Bricks/VibrationBrickTests.swift

Created new regression tests for the getFormulas method of the BrickFormulaProtocol. This is part 4 of 4, added test to following classes:
SetXBrickTests
SetYBrickTests
TurnLeftBrickTests
TurnRightBrickTests
VibrationBrickTests
ChangeVolumeByNBrickTests (new class)
SetVolumeToBrickTests (new class)
SpeakAndWaitBrickTests (new class)
SpeakBrickTests (new class)
DeleteItemOfUserListBrickTests
AddItemToUserListBrickTests
ChangeVariableBrickTests
ReplaceItemInUserListBrickTests
InsertItemIntoUserListBrickTests
ShowTextBrickTests
SetVariableBrick

CATTY-287 Add tests for BrickFormulaProtocol 4/4

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/Bricks/ChangeTransparencyByNBrickTests.swift
src/CattyTests/Bricks/PhiroMotorMoveBackwardBrickTests.swift
src/CattyTests/Bricks/PhiroMotorMoveForwardBrickTests.swift
src/CattyTests/Bricks/PhiroPlayToneBrickTests.swift
src/CattyTests/Bricks/PhiroRGBLightBrickTests.swift
src/CattyTests/Bricks/SayBubbleBrickTests.swift
src/CattyTests/Bricks/SayForBubbleBrickTests.swift
src/CattyTests/Bricks/SetBrightnessBrickTests.swift
src/CattyTests/Bricks/SetColorBrickTests.swift
src/CattyTests/Bricks/SetTransparencyBrickTests.swift

Created new regression tests for the getFormulas method of the BrickFormulaProtocol. This is part 2 of 4, added test to following classes:
PhiroMotorMoveBackwardBrickTests (new class)
PhiroMotorMoveForwardBrickTests (new class)
PhiroPlayToneBrickTests (new class)
PhiroRGBLightBrickTests (new class)
ChangeTransparencyByNBrickTests
SayBubbleBrickTests (new class)
SayForBubbleBrickTests (new class)
SetBrightnessBrickTests
SetColorBrickTests
SetTransparencyToBrickTests

CATTY-285 Add tests for BrickFormulaProtocol 2/4

---

src/CattyTests/DataModel/LookTest.swift

CATTY-432 Add tests for Look

---

src/Catty/ViewController/MediaLibrary/ContentViews/LibraryImageCollectionViewCell.swift

The border for the items of the Media library should be removed.

CATTY-443 Media library without borders

---

src/CattyTests/Bricks/PointToBrickTests.swift
src/CattyTests/Bricks/PreviousLookBrickTests.swift
src/CattyTests/Bricks/ReplaceItemInUserListBrickTests.swift
src/CattyTests/Bricks/SetBrightnessBrickTests.swift
src/CattyTests/Bricks/SetColorBrickTests.swift
src/CattyTests/Bricks/SetSizeToBrickTests.swift
src/CattyTests/Bricks/SetTransparencyBrickTests.swift
src/CattyTests/Bricks/SetVariableBrickTests.swift

Added tests for mutable copy to other bricks

CATTY-206 Add tests for mutable copy (part 3)

---

Jenkinsfile.screenshots
src/Catty.xcodeproj/project.pbxproj
src/Catty/ViewController/BaseViewController/BaseCollectionViewController.m
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/ObjectTableViewController.m
src/Catty/ViewController/Continue&New/SceneTableViewController.m
src/Catty/Views/Custom/Button/PlayButton.swift
src/CattyUISnapshots/CattyUISnapshots.swift
src/fastlane/Snapfile

Created a new Jenkins job that automate the screenshot creating on different devices in different languages. 
GitHub branch of the Jenkins release job needs to be changed, when PR gets merged. https://jenkins.catrob.at/job/Release/job/Catty_Screenshots_Test/

CATTY-460 Jenkins job for UI screenshots

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/PocketPaint/ViewController/TextInputViewController.m
src/CattyTests/ViewController/TextInputViewControllerTests.swift

It was the same bug as in "CATTY-102 Fix "Done"-Button and Status-Bar". Same Solution as well.

CATTY-467: Buttons not visible at Text-Tool

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/Bricks/ChangeSizeByNBrickTests.swift
src/CattyTests/Bricks/ChangeXByNBrickTests.swift
src/CattyTests/Bricks/ChangeYByNBrickTests.swift
src/CattyTests/Bricks/GlideToBrickTests.swift
src/CattyTests/Bricks/GoNStepsBackBrickTests.swift
src/CattyTests/Bricks/MoveNStepsBrickTests.swift
src/CattyTests/Bricks/PlaceAtBrickTests.swift
src/CattyTests/Bricks/PointInDirectionBrickTests.swift
src/CattyTests/Bricks/ThinkBubbleBrickTests.swift
src/CattyTests/Bricks/ThinkForBubbleBrickTests.swift

Created new regression tests for the getFormulas method of the BrickFormulaProtocol. This is part 3 of 4, added test to following classes:
ThinkBubbleBrickTests (new class)
ThinkForBubbleBrickTests (new class)
ChangeSizeByNBrickTests
ChangeXByNBrickTests (new class)
ChangeYByNBrickTests (new class)
GlideToBrickTests
GoNStepsBackBrickTests
MoveNStepsBrickTests
PlaceAtBrickTests
PointInDirectionBrickTests

CATTY-286 Add tests for BrickFormulaProtocol 3/4

---

Jenkinsfile

Archive build artifacts before test run

CATTY-479 Archive build artifacts before test run

---

Jenkinsfile
Jenkinsfile.release
Jenkinsfile.screenshots

CATTY-480 Update Jenkins files

---

src/Catty/DataModel/Bricks/Control/BroadcastBrick.m
src/Catty/DataModel/Bricks/Control/BroadcastWaitBrick.m
src/Catty/DataModel/Scripts/BroadcastScript.m
src/Catty/DataModel/Scripts/StartScript.m
src/Catty/DataModel/Scripts/WhenBackgroundChangesScript.swift
src/Catty/DataModel/Scripts/WhenConditionScript.swift
src/Catty/DataModel/Scripts/WhenScript.m
src/Catty/DataModel/Scripts/WhenTouchDownScript.m
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Defines/UIDefines.h
src/Catty/Defines/UIDefines.swift
src/Catty/Extension&Delegate&Protocol/Extensions/UIColorExtension.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryOverviewController.swift
src/CattyUITests/CreateProjectTests.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
src/CattyUITests/ScriptCollectionView/BrickCellPickerViewerTest.swift
src/CattyUITests/ScriptCollectionView/ScriptCollectionVCTests.swift

Created new "event" category and added following Bricks to the new category:
- When project starts
- When tapped
- When stage is tapped
- When you receive
- Broadcast
- Broadast and wait
- When becomes true
- When background changes to
!! Also changed height of category overview bricks !!

CATTY-478 New Event category

---

src/CattyUISnapshots/CattyUISnapshots.swift

CATTY-485 Rename files for screenshots

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/PlayerEngine/Instructions/Look/SetBackgroundBrick+Instruction.swift
src/CattyTests/Bricks/SetBackgroundBrickTests.swift
src/CattyTests/Bricks/SetLookBrickTests.swift
src/CattyTests/Mocks/LookMock.swift
src/CattyTests/Mocks/RuntimeImageCacheMock.swift

Fix instruction for SetBackground- and SetLookBrick

CATTY-488 Fix instruction for SetBackground- and SetLookBrick

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/LaunchArguments.swift
src/Catty/Supporting Files/AppDelegate.swift
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/CattyUITests/BackgroundsTests.swift
src/CattyUITests/CreateProjectTests.swift
src/CattyUITests/Extensions/XCTestCaseExtension.swift
src/CattyUITests/LooksTVCTests.swift
src/CattyUITests/MyFirstProjectTests.swift
src/CattyUITests/ObjectTVCTests.swift
src/CattyUITests/PocketCodeMainScreenTests.swift
src/CattyUITests/PrivacyPolicyVCTests.swift
src/CattyUITests/ProjectTVCTests.swift
src/CattyUITests/ProjectsTVCTests.swift
src/CattyUITests/ScriptCollectionView/BrickCellPickerViewerTest.swift
src/CattyUITests/ScriptCollectionView/BrickCellTests.swift
src/CattyUITests/ScriptCollectionView/ListTests.swift
src/CattyUITests/ScriptCollectionView/ScriptCollectionVCTests.swift
src/CattyUITests/ScriptCollectionView/VariableTests.swift
src/CattyUITests/SoundsTVCTests.swift

CATTY-375 Increase UI test speed

---

src/Cartfile
src/Cartfile.resolved
src/Catty.xcodeproj/project.pbxproj

Remove unused/deprecated dependency "M13ProgressSuite":
Cartfile (+resolved)
Xcode project file (Build phase + linked framework)

CATTY-486 Remove deprecated dependency M13ProgressSuite

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryOverviewController.swift

Update layout of overview (parent) by calling the setup method in `viewWillAppear` and removing it from `viewDidLoad`.

CATTY-483 Landscape mode for Brick overview

---

src/Catty/Storyboard+XIB/LaunchScreen.storyboard

Update the launch screen of Catty so that it says 2010-2021. Make sure to only change the year and no other things of the xib file.

CATTY-501 Update year in launch screen

---

src/Catty/Defines/UIDefines.h

removed unsued defines in UIDefines

CATTY-477 remove unused defines in UIDefines

---

src/Catty/DataModel/Scene/Scene.swift

Removed "saved" notification when creating new projects or objects. 

CATTY-510 Removed "saved" notification when creating new projects or objects

---

src/CattyTests/Formula/FormulaTest.swift

Add missing tests for the getDisplayString method of the Formula. Add those tests in FormulaTest.swift and make sure to add at least two tests: one verifying the behavior without a displayString manually set and one with a displayString manually set.

CATTY-513 Add missing tests for Formula display string

---

src/Catty/DataModel/Bricks/Embroidery/StitchBrick.swift
src/Catty/DataModel/Bricks/Look/SetLookByIndexBrick.swift
src/Catty/Extension&Delegate&Protocol/Extensions/SpriteNode/CBSpriteNodeEmbroideryExtension.swift
src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/ProjectDetailStoreViewControllerExtension.swift
src/Catty/Extension&Delegate&Protocol/Extensions/URLSessionMultipartExtension.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Embroidery/StitchBrick+CBXMLHandler.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/LookBricks/SetLookByIndexBrick+CBXMLHandler.swift
src/Catty/PlayerEngine/DataModel/CircleShapeNode.swift
src/Catty/PlayerEngine/Instructions/Embroidery/StitchBrick+Instruction.swift
src/Catty/SetLookByIndexBrick+Instruction.swift
src/Catty/Store/StoreProjectReporter.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Embroidery/StitchBrickCell.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SetLookByIndexBrickCell.swift
src/CattyTests/Bricks/SetLookByIndexBrickTests.swift
src/CattyTests/Bricks/StitchBrickTests.swift
src/CattyTests/CBSpriteNodeStitchExtensionTests.swift
src/CattyTests/CircleShapeNodeTests.swift
src/CattyTests/Store/Report/StoreProjectReporterTests.swift
src/CattyTests/URLSessionMultipartExtensionTests.swift

Change license header in 19 Files.

CATTY-529: Change license header to 2021

---

src/Catty/BluetoothHelper/BluetoothHelper/Components/CentralManager.swift
src/Catty/BluetoothHelper/BluetoothHelper/Components/Peripheral.swift
src/Catty/BluetoothHelper/BluetoothHelper/Components/Service.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLValidator.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/VariablesContainer/UserDataContainer+CBXMLHandler.m
src/Catty/PocketPaint/ViewController/PaintViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickManager/BrickMoveManager.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController.m
src/Catty/ViewController/Upload/LoginViewController.m
src/Catty/ViewController/Upload/RegisterViewController.m
src/CattyTests/Parser & Serialization/CatrobatLanguage0.95/XMLParserTests/Unit Tests/XMLParserBrickTests095.swift
src/CattyTests/TestHelpers/ConvertExceptionToError.m

CATTY-509 Replace deprecated NSLog statements with custom Logger

---

src/Catty/Helpers/Util/TableUtil.m
src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m
src/Catty/Helpers/Util/Util.swift
src/CattyTests/Utils/UtilTests.swift

Convert the following methods of Util.m (and Util.h) to Util.swift:
- screenSize:
- screenHeight:
- screenWidth
- screenHeight
- screenWidth
- statusBarHeight
Add tests to UtilTests.swift in case they do not exist yet.

CATTY-522 Convert Util methods to Swift 1/3

---

src/Catty.xcodeproj/project.pbxproj

CATTY-545 Update iOS Deployment Target

---

src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m
src/Catty/Helpers/Util/Util.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellMessageData.m
src/CattyTests/Utils/UtilTests.swift

CATTY-524 Convert Util methods to Swift 3/3
The following methods of Util.m (and Util.h) have been converted to Swift (Util.swift):
objectWithName:forScene:
soundWithName:forObject:
lookWithName:forObject:
allMessagesForProject
And following *new* tests in UtilTests.swift have been written:
testLookWithNameForObject()
testObjectWithNameForScene()
testSoundWithNameForObject()

CATTY-524 Convert Util methods to Swift 3/3

---

src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift

Implements https://jira.catrob.at/browse/CATTY-563
Also removed some unnecessary code left from TTTAtributedLabel.

CATTY-563 Hashtag in description

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/ViewController/Stage/StagePresenterSideMenuView.swift
src/Catty/ViewController/Stage/StagePresenterViewController.m
src/Catty/ViewController/Stage/StagePresenterViewControllerShareExtension.swift
src/CattyTests/ViewController/Stage/StagePresenterSideMenuViewTests.swift

There is a little area between the icons and the labels which is not clickable. Instead, all the space between the icons and the labels should be clickable. Label and Button has now no space in between and added padding top to label.

CATTY-577 Unclickable area in side menu

---

src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift

CATTY-582 Do not parse on main thread

CATTY-582 Do not parse on main thread

---

src/Cartfile
src/Cartfile.resolved
src/Catty.xcodeproj/project.pbxproj
src/Catty.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
src/Catty/IO/FileManager/CBFileManager.m

See https://jira.catrob.at/projects/CATTY/issues/CATTY-589

CATTY-589 Update ZipArchive to latest version

---

src/Catty.xcodeproj/project.pbxproj
src/Catty.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
src/Catty/DataModel/Bricks/Look/SetBackgroundByIndexBrick.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/LookBricks/SetBackgroundByIndexBrick+CBXMLHandler.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
src/Catty/PlayerEngine/Instructions/Look/SetBackgroundByIndexBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/SetLookByIndexBrick+Instruction.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SetBackgroundByIndexBrickCell.swift
src/CattyTests/Bricks/SetBackgroundByIndexBrickTests.swift
src/CattyTests/Parser & Serialization/CatrobatLanguage0.992/XMLParserTests/Unit Tests/XMLParserTests0992.swift
src/CattyTests/PlayerEngine/CBSpriteNodeTests.swift
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0992.xml
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
src/CattyUITests/SceneTVCTests.swift

Implemented a new Brick called "SetBackgroundByIndexBrick". This Brick change the Look of the background object to a look identified by a given number

CATTY-395 Implement SetBackgroundByIndexBrick

---

src/Catty/Supporting Files/Firebase/GoogleService-Info.plist

CATTY-593 Change placeholder for Firebase API key. For details see https://jira.catrob.at/browse/CATTY-593.

CATTY-593 Change placeholder for Firebase API key

---

README.md

CATTY-608-Add-minimum-required-Xcode-version-to-README

---

src/Catty/Functions/Math/AcosFunction.swift
src/Catty/Functions/Math/AsinFunction.swift
src/Catty/Functions/Math/AtanFunction.swift
src/CattyTests/Formula/FormulaParserFunctionsTest.m
src/CattyTests/PlayerEngine/Functions/Math/AcosFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/AsinFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/AtanFunctionTest.swift
src/CattyTests/Resources/ParserTests/Custom/Functions/Functions_0993.xml
src/CattyTests/Resources/ParserTests/Custom/Functions/Functions_0994.xml
src/CattyTests/XML/Parser/CatrobatLanguage0.993/XMLParserTests0993.swift
src/CattyTests/XML/Parser/CatrobatLanguage0.994/XMLParserTests0994.swift

Add all missing functions from the formula editor to Function_0993.xml.

CATTY-605-Add-missing-functions-to-Function_0993.xml

---

src/Gemfile

CATTY-615 Update Gemfile

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Array/SynchronizedArray.swift
src/Catty/DataModel/UserData/UserList.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Functions/List/IndexOfItemFunction.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Functions.swift
src/CattyTests/DataModel/SynchronizedArrayTests.swift
src/CattyTests/DataModel/UserListTest.swift
src/CattyTests/Formula/UserListFunctionsTest.swift
src/CattyTests/PlayerEngine/Functions/List/IndexOfItemFunctionTest.swift
src/CattyTests/Resources/ParserTests/Custom/Functions/Functions_0994.xml
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

Returns the index of the first occurrence of the item in the list. Items can be numbers or text. The numbering starts with 1. If the item is not contained in the list, return 0. If the list is empty, return 0. If the item is the empty string '' and the list contains also one or more items that are empty string, then return the index of the first occurrence of such an empty string in the list.
The function shall be available in the formula editor under the "Function" button as the last entry, below the "contains( list name )" function's entry.

CATTY-541-PPPP-"items-index(abc,-list-name-)"-function

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/Resources/ParserTests/Custom/Data/UserData_0996.xml
src/CattyTests/Resources/ParserTests/Custom/Data/UserVariables_0996.xml
src/CattyTests/Resources/ParserTests/Custom/DisabledBricks/DisabledBricks_0996.xml
src/CattyTests/Resources/ParserTests/Custom/Encapsulated/Encapsulated_0996.xml
src/CattyTests/Resources/ParserTests/Custom/EscapingChars/EscapingChars_0996.xml
src/CattyTests/Resources/ParserTests/Custom/Functions/Functions_0996.xml
src/CattyTests/Resources/ParserTests/Custom/GoToBricks/GoToBrick_0996.xml
src/CattyTests/Resources/ParserTests/Custom/ListBricks/AddItemToUserListBrick0996.xml
src/CattyTests/Resources/ParserTests/Custom/LogicBricks/LogicBricks_0996.xml
src/CattyTests/Resources/ParserTests/Custom/Object/collisionTest0996.xml
src/CattyTests/Resources/ParserTests/Custom/Sensors/Sensors_0996.xml
src/CattyTests/Resources/ParserTests/Custom/ValidHeader/ValidHeader0996.xml
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Air_fight_0.5/Air_fight_0.5_0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Airplane_with_shadow/Airplane_with_shadow_0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Demonstration/Demonstration_0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Flap_Pac_Man/Flap_Pac_Man_0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Flappy_v3.0/Flappy_v3.0_0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Galaxy_War/Galaxy_War_0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Memory/Memory_0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Piano/Piano_0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Pong_Starter/Pong_Starter_0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Pythagorean_Theorem/Pythagorean_Theorem_0996.xml
src/CattyTests/Resources/ParserTests/UserProjects/Tic_Tac_Toe_Master/Tic_Tac_Toe_Master_0996.xml

CATTY-613 Add XML files for Catrobat Language Version 0.996

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/Resources/ParserTests/Custom/Data/UserLists_0998.xml
src/CattyTests/Resources/ParserTests/Custom/Data/UserVariables_0998.xml
src/CattyTests/Resources/ParserTests/Custom/DisabledBricks/DisabledBricks_0998.xml
src/CattyTests/Resources/ParserTests/Custom/Encapsulated/Encapsulated_0998.xml
src/CattyTests/Resources/ParserTests/Custom/EscapingChars/EscapingChars_0998.xml
src/CattyTests/Resources/ParserTests/Custom/Functions/Functions_0998.xml
src/CattyTests/Resources/ParserTests/Custom/GoToBricks/GoToBrick_0998.xml
src/CattyTests/Resources/ParserTests/Custom/LogicBricks/LogicBricks_0998.xml
src/CattyTests/Resources/ParserTests/Custom/Object/collisionTest0998.xml
src/CattyTests/Resources/ParserTests/Custom/Sensors/Sensors_0998.xml
src/CattyTests/Resources/ParserTests/Custom/ValidHeader/ValidHeader0998.xml
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Air_fight_0.5/Air_fight_0.5_0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Airplane_with_shadow/Airplane_with_shadow_0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Demonstration/Demonstration_0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Flap_Pac_Man/Flap_Pac_Man_0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Flappy_v3.0/Flappy_v3.0_0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Galaxy_War/Galaxy_War_0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Memory/Memory_0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Piano/Piano_0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Pong_Starter/Pong_Starter_0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Pythagorean_Theorem/Pythagorean_Theorem_0998.xml
src/CattyTests/Resources/ParserTests/UserProjects/Tic_Tac_Toe_Master/Tic_Tac_Toe_Master_0998.xml

added all XML files for CBL 0.998

CATTY-617 added all XML files for CBL 0.998

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/Resources/ParserTests/Custom/Data/UserLists_09993.xml
src/CattyTests/Resources/ParserTests/Custom/Data/UserVariables_09993.xml
src/CattyTests/Resources/ParserTests/Custom/DisabledBricks/DisabledBricks_09993.xml
src/CattyTests/Resources/ParserTests/Custom/Encapsulated/Encapsulated_09993.xml
src/CattyTests/Resources/ParserTests/Custom/EscapingChars/EscapingChars_09993.xml
src/CattyTests/Resources/ParserTests/Custom/Functions/Functions_09993.xml
src/CattyTests/Resources/ParserTests/Custom/GoToBricks/GoToBrick_09993.xml
src/CattyTests/Resources/ParserTests/Custom/LogicBricks/LogicBricks_09993.xml
src/CattyTests/Resources/ParserTests/Custom/Object/collisionTest09993.xml
src/CattyTests/Resources/ParserTests/Custom/Sensors/Sensors_09993.xml
src/CattyTests/Resources/ParserTests/Custom/ValidHeader/ValidHeader09993.xml
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Air_fight_0.5/Air_fight_0.5_09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Airplane_with_shadow/Airplane_with_shadow_09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Demonstration/Demonstration_09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Flap_Pac_Man/Flap_Pac_Man_09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Flappy_v3.0/Flappy_v3.0_09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Galaxy_War/Galaxy_War_09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Memory/Memory_09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Piano/Piano_09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Pong_Starter/Pong_Starter_09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Pythagorean_Theorem/Pythagorean_Theorem_09993.xml
src/CattyTests/Resources/ParserTests/UserProjects/Tic_Tac_Toe_Master/Tic_Tac_Toe_Master_09993.xml

CATTY-620  added XML files for CBL 09993
**MERGE #1683  BEFORE THIS!**

CATTY-620  added XML files for CBL 09993

---

src/Catty/DataModel/Scene/Scene.swift
src/Catty/DataModel/SpriteObject/SpriteObject.h
src/Catty/DataModel/SpriteObject/SpriteObject.m
src/Catty/IO/ProjectManager.swift
src/Catty/Supporting Files/AppDelegate.swift
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Continue&New/SceneTableViewController.m
src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.h
src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.m
src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift
src/Catty/ViewController/Projects/MyProjectsViewController.m
src/CattyTests/Bricks/ChangeBrightnessByNBrickTests.swift
src/CattyTests/Bricks/ChangeColorByNBrickTests.swift
src/CattyTests/Bricks/ClearGraphicEffectBrickTests.swift
src/CattyTests/Bricks/SetBackgroundByIndexBrickTests.swift
src/CattyTests/Bricks/SetBrightnessBrickTests.swift
src/CattyTests/Bricks/SetColorBrickTests.swift
src/CattyTests/Bricks/SetLookByIndexBrickTests.swift
src/CattyTests/DataModel/LookTest.swift
src/CattyTests/DataModel/SceneTest.swift
src/CattyTests/FileManager/ProjectManagerTests.swift
src/CattyTests/Mocks/CBFileManagerMock.swift
src/CattyTests/PlayerEngine/CBBackendTests.swift
src/CattyTests/ViewController/Stage/StagePresenterViewControllerScreenshotTests.swift
src/CattyTests/ViewController/Stage/StagePresenterViewControllerTests.swift
src/CattyTests/XML/Helper/CBXMLParserHelperTests.swift

Deleting one single object does and reopening the project will get back the previously "deleted" object. That's because the project is not being saved when deleting one single object.
Currently, removeObjects is calling saveToDisk and removeObject is not. In fact the data model should NOT be related with persisting data on the file system in any way. Therefore this ticket should also include some refactoring:
ProjectManager should get a new method removeObjects(project: Project, objects: [SpriteObject])
This method should replace the removeObjects method from the data model PLUS persist the project. One method (plural) should be enough and you can remove the removeObjects method from the data model.
As another refactoring, make all methods in the ProjectManager instance methods, not class …

CATTY-515 Delete object not working and refactoring

---

src/fastlane/Snapfile

Adds localized screenshots of Portuguese (Brazil) and Spanish language.

CATTY-592 Add localized screenshots for Portuguese (Brazil) and Spanish

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Embroidery/StartRunningStitchBrick.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Embroidery/EmbroideryDefines.swift
src/Catty/Embroidery/EmbroideryStream.swift
src/Catty/Embroidery/Pattern/RunningStitchPattern.swift
src/Catty/Embroidery/Pattern/StitchPatternProtocol.swift
src/Catty/Extension&Delegate&Protocol/Extensions/CGPointExtentions.swift
src/Catty/Extension&Delegate&Protocol/Extensions/SpriteNode/CBSpriteNodeSensorExtension.swift
src/Catty/PlayerEngine/Instructions/Embroidery/StartRunningStitchBrick+Instruction.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Embroidery/StartRunningStitchBrickCell.swift
src/Catty/XML/XMLHandler/Bricks/Embroidery/StartRunningStitchBrick+CBXMLHandler.swift
src/CattyTests/Bricks/StartRunningStitchBrickTests.swift
src/CattyTests/Embroidery/RunningStitchPatternTests.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

To further improve the embroidery feature a new Start running stitch with length n Brick shall be implemented. After this Brick is executed a Stich is placed ever n steps an object moves. 

CATTY-604: Start running stitch Brick

---

src/Catty.xcodeproj/project.pbxproj
src/Catty.xcodeproj/xcshareddata/xcschemes/Catty (DEBUG).xcscheme
src/Catty/DataModel/Bricks/Data/WebRequestBrick.swift
src/Catty/Defines/ProjectDefines.h
src/Catty/PlayerEngine/Instructions/Data/WebRequestBrick+Instruction.swift
src/Catty/Supporting Files/AppDelegate.swift
src/Catty/ViewController/AlertController/AlertController.swift
src/Catty/ViewController/AlertController/AlertControllerBuilder.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/CattyTests/Bricks/WebRequestBrickTests.swift
src/CattyTests/Mocks/AlertControllerBuilderMock.swift
src/CattyUITests/FormulaEditorKeyboardTests.swift
src/CattyUITests/LooksTVCTests.swift
src/CattyUITests/MyFirstProjectTests.swift
src/CattyUITests/ObjectTVCTests.swift
src/CattyUITests/PocketCodeMainScreenTests.swift
src/CattyUITests/ProjectTVCTests.swift
src/CattyUITests/ScriptCollectionView/ListTests.swift
src/CattyUITests/ScriptCollectionView/ScriptCollectionVCTests.swift
src/CattyUITests/ScriptCollectionView/VariableTests.swift
src/CattyUITests/SoundsTVCTests.swift
src/fastlane/Fastfile

CATTY-631 Run tests in parallel

---

README.md
src/Catty/Storyboard+XIB/LaunchScreen.storyboard
src/Catty/Supporting Files/AppDelegate.swift
src/Catty/ViewController/BaseViewController/BaseTableViewController.m
src/Catty/ViewController/Download/DownloadTabBarController.m

https://jira.catrob.at/projects/CATTY/issues/CATTY-628?filter=allopenissues

CATTY-628 Adapt to to Navbar/Toolbar style changes in iOS 15 SDK

---

src/Catty/Helpers/NavigationController/NavigationController.m
src/Catty/Storyboard+XIB/iPhone.storyboard
src/Catty/Supporting Files/AppDelegate.swift
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m

https://jira.catrob.at/browse/CATTY-583
Removed some now unused orientation code, resolved layout constraint conflict, also disabled scrolling on devices with safe areas.

CATTY-583 Problem with LayoutConstraints on main screen

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

https://jira.catrob.at/browse/CATTY-634

CATTY-634 Delete Bricks with iOS 15

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/NetworkDefines.swift
src/Catty/Store/StoreProjectDownloader.swift
src/Catty/Store/StoreProjectUploader.swift
src/Catty/ViewController/Download/SearchStore/SearchStoreViewController.swift
src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.searchProjects.success.specialCharacters.json
src/CattyTests/Store/Download/StoreProjectDownloaderTests.swift

https://jira.catrob.at/projects/CATTY/issues/CATTY-633?filter=allopenissues
Fix URL encoding to allow spaces and special/UTF-8 characters in searches.
Also adds a delay to searches while typing to avoid DDoSing the share

CATTY-633 Search project with query consisting of multiple words

---

src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m

https://jira.catrob.at/browse/CATTY-644

CATTY-644 Layout problems on main screen

---

src/Catty/XML/Parser/CBXMLParser.m

https://jira.catrob.at/browse/CATTY-642

CATTY-642 Disable XML output when parsing project

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
src/Catty/PlayerEngine/Sensors/Object/TouchesEdgeSensor.swift
src/Catty/PlayerEngine/Stage/Stage.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Sensors.swift
src/CattyTests/PlayerEngine/Sensors/Object/TouchesEdgeSensorTest.swift
src/CattyTests/Resources/ParserTests/Custom/Sensors/TouchesEdgeSensor.xml
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

https://jira.catrob.at/browse/CATTY-551
Add a new sensor to the "Object" (or later "Properties") section of the Formula Editor (subsection "Motion properties"). This sensor should be named "touches edge".
The sensor should evaluate to "1" once the object (or background) touches the edge of the screen. Otherwise it should evaluate to "0".
The sensor should not detect a collision in case a transparent part of the Look touches the edge. However, it should still be detected in case the object is hidden.
The sensor should be serialized as COLLIDES_WITH_EDGE. Do not forget to add tests and add this sensor to ValidFormulaList.xml (or create an individual xml).
Please review the [contributing guidelines](https://github.com/Catrobat/Catty/blob/develop/README.md) and [wiki …

CATTY-551 PPPP: Add "touches edge" sensor

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/CattyUITests/ScriptCollectionView/BrickMovementTests.swift

When moving a brick sometimes it won't be saved. This PR should solve that issue.

CATTY-511 fix movement of bricks

---

src/CattyUITests/TrustedDomainTVCTests.swift

https://jira.catrob.at/browse/CATTY-649

CATTY-649 Fix flaky TrustedDomainTVCTests

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/SceneTableViewControllerExtension.swift
src/Catty/Helpers/Util/Util.swift
src/Catty/Storyboard+XIB/LaunchScreen.storyboard
src/Catty/Storyboard+XIB/iPhone.storyboard
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.h
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Continue&New/SceneTableViewController.m
src/Catty/ViewController/Upload/LoginViewController.h
src/Catty/ViewController/Upload/LoginViewController.m
src/Catty/ViewController/Upload/RegisterViewController.h
src/Catty/ViewController/Upload/RegisterViewController.m
src/CattyUITests/SceneTVCTests.swift

https://jira.catrob.at/browse/CATTY-594

CATTY-594 Add option upload option

---

src/CattyUITests/ScriptCollectionView/BrickMovementTests.swift

https://jira.catrob.at/browse/CATTY-650

CATTY-650 Fix flaky BrickMovementTests

---

src/Catty/PlayerEngine/AudioEngine/AudioEngine.swift

https://jira.catrob.at/browse/CATTY-667

CATTY-667 Check if AudioEngine is running before resuming AudioPlayers

---

src/Catty/DataModel/Project/Project.h
src/Catty/DataModel/Project/Project.m
src/Catty/Helpers/BrickHelpers/CameraPreviewHandler.m
src/Catty/XML/Parser/CBXMLParser.m
src/Catty/XML/Serializer/CBXMLSerializer.m

(https://jira.catrob.at/browse/CATTY-672)
- also fixes the issue with starting projects before the are saved (using a lock)

CATTY-672 Fix camera brick is using wrong camera

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Helpers/BrickHelpers/CameraPreviewHandler.m
src/Catty/ViewController/Stage/StagePresenterViewController.m
src/Catty/ViewController/Stage/StagePresenterViewControllerOrientation.swift

https://jira.catrob.at/browse/CATTY-685
- also fixes wrong camera orientation in landscape mode

CATTY-685 Fix rotating device in scene

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Functions/ObjectRecognition/XOfObjectWithIDFunction.swift
src/Catty/Functions/ObjectRecognition/YOfObjectWithIDFunction.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Functions.swift
src/CattyTests/PlayerEngine/Functions/ObjectRecognition/ObjectRecognitionFunctionsTest.swift
src/CattyTests/PlayerEngine/Sensors/Mocks/VNRecognizedObjectObservationMock.swift
src/CattyTests/PlayerEngine/Sensors/Mocks/VisualDetectionManagerMock.swift
src/CattyTests/Resources/ParserTests/Custom/Sensors/ObjectRecognitionSensors.xml
src/CattyTests/XML/Parser/CatrobatLanguage0.9993/XMLParserTests09993.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

https://jira.catrob.at/browse/CATTY-675
FYI: The object detection model (Tiny YOLOv3) detects the location of up to 80 different objects from the COCO dataset (the list of objects can be found here: https://github.com/pjreddie/darknet/blob/master/data/coco.names)
**Pocket-Code App/Demonstration to test all added features:**
_ObjectDetection2_
Move your camera over a object that is contained in the list from above and a circle at the center position of the detected object will appear. The demonstration app shows the names of up to three different objects.
https://share.catrob.at/app/project/e92f5959-dda9-489e-b954-9c83aea5ea44
[ObjectDetection2.catrobat.zip](https://github.com/Catrobat/Catty/files/9062399/ObjectDetection2.catrobat.zip)
Please review the [contributing …

CATTY-675 Implement object detection position reporter functions

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Functions/ObjectRecognition/HeightOfObjectWithIDFunction.swift
src/Catty/Functions/ObjectRecognition/WidthOfObjectWithIDFunction.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Functions.swift
src/CattyTests/PlayerEngine/Functions/ObjectRecognition/ObjectRecognitionFunctionsTest.swift
src/CattyTests/Resources/ParserTests/Custom/Sensors/ObjectRecognitionSensors.xml
src/CattyTests/XML/Parser/CatrobatLanguage0.9993/XMLParserTests09993.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

https://jira.catrob.at/browse/CATTY-676
FYI: The object detection model (Tiny YOLOv3) detects the location of up to 80 different objects from the COCO dataset (the list of objects can be found here: https://github.com/pjreddie/darknet/blob/master/data/coco.names)
**Pocket-Code App/Demonstration to test all added features:**
_ObjectDetection3_
Move your camera over a object that is contained in the list from above and four circles at the corner positions of the detected object will appear - indicating the bounding box dimensions.
https://share.catrob.at/app/project/b0e30b08-ea7a-46fa-989e-b3cada81c981
[ObjectDetection3.catrobat.zip](https://github.com/Catrobat/Catty/files/9063156/ObjectDetection3.catrobat.zip)
[Demonstration Video](https://user-images.githubusercontent.com/60399652/17776373 …

CATTY-676 Implement object detection size reporter functions

---

src/.swiftlint.auto.yml
src/.swiftlint.yml
src/Catty.xcodeproj/project.pbxproj
src/Catty.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
src/Catty/BluetoothDevice/FirmataDevices/Arduino/ArduinoDevice.swift
src/Catty/BluetoothHelper/BluetoothHelper/Components/CentralManager.swift
src/Catty/BluetoothHelper/BluetoothHelper/Components/Peripheral.swift
src/Catty/BluetoothHelper/BluetoothHelper/Components/Service.swift
src/Catty/BluetoothHelper/BluetoothHelper/Helper/BluetoothHelper.swift
src/Catty/BluetoothHelper/BluetoothHelper/Helper/SimpleFutures.swift
src/Catty/BluetoothHelper/BluetoothHelperTests/RawSerializerDeserializerTests.swift
src/Catty/DataModel/Scene/Scene.swift
src/Catty/DataModel/UserDataContainer/UserDataContainer.swift
src/Catty/Extension&Delegate&Protocol/Extensions/BrickExtension.swift
src/Catty/FormulaEditor/ViewController/FormulaEditorSectionViewController/FormulaEditorDataSectionViewController.swift
src/Catty/Helpers/Firmata/Firmata.swift
src/Catty/Helpers/Util/Util.swift
src/Catty/IO/ProjectManager.swift
src/Catty/PlayerEngine/DataModel/CBSequence/CBConditionalSequence.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryOverviewController.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/CattyTests/BluetoothDevices/Firmata/FirmataTests.swift
src/CattyTests/PlayerEngine/AudioEngine/IntegrationTests/AudioPlayerIntegrationTests.swift
src/CattyTests/PlayerEngine/AudioEngine/Mocks/AudioEngineFingerprintingStub.swift
src/CattyTests/PlayerEngine/Functions/Arduino/ArduinoAnalogPinFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Arduino/ArduinoDigitalPinFunctionTest.swift
src/CattyTests/Store/Upload/StoreProjectUploaderTests.swift
src/CattyTests/Utils/UtilTests.swift
src/CattyUITests/Extensions/XCTestCaseExtension.swift

https://jira.catrob.at/browse/CATTY-687

CATTY-687 Xcode 14 compatibility

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/NetworkDefines.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController+MediaLibrary.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController+MediaLibrary.swift
src/Catty/ViewController/MediaLibrary/MediaItem.swift
src/Catty/ViewController/MediaLibrary/MediaLibraryCollectionViewDataSource.swift
src/Catty/ViewController/MediaLibrary/MediaLibraryDownloader.swift
src/Catty/ViewController/MediaLibrary/MediaType.swift
src/CattyTests/MediaLibrary/Fixtures/MediaLibraryDownloader.downloadData.fail.request.json
src/CattyTests/MediaLibrary/Fixtures/MediaLibraryDownloader.downloadData.success.json
src/CattyTests/MediaLibrary/Fixtures/MediaLibraryDownloader.downloadIndex.fail.parse.json
src/CattyTests/MediaLibrary/Fixtures/MediaLibraryDownloader.downloadIndex.fail.request.json
src/CattyTests/MediaLibrary/Fixtures/MediaLibraryDownloader.downloadIndex.success.json
src/CattyTests/MediaLibrary/MediaItemTest.swift
src/CattyTests/MediaLibrary/MediaLibraryCollectionViewDataSourceTests.swift
src/CattyTests/MediaLibrary/MediaLibraryDownloaderTests.swift
src/CattyTests/Store/Download/StoreProjectDownloaderTests.swift

https://jira.catrob.at/browse/CATTY-688

CATTY-688 Adapt media library to updated API

---

src/Catty/Embroidery/EmbroideryDefines.swift

CATTY-697 Check & Align Embroidery bricks to Catroid

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.swift
src/CattyTests/Store/Authenticate/Fixtures/StoreAuthenticator.deleteUser.success.refresh.json
src/CattyTests/Store/Authenticate/Fixtures/StoreAuthenticator.deleteUser.success.upgrade.json
src/CattyTests/Store/Authenticate/StoreAuthenticatorTests.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

CATTY-703 Add Account deletion feature

---

src/Catty/Embroidery/EmbroideryDSTHeader.swift
src/Catty/Embroidery/EmbroideryDSTService.swift
src/Catty/Embroidery/EmbroideryStream.swift
src/Catty/Embroidery/Pattern/RunningStitchPattern.swift
src/Catty/Embroidery/Pattern/StitchPatternProtocol.swift
src/Catty/Embroidery/Pattern/ZigzagStitchPattern.swift
src/Catty/Extension&Delegate&Protocol/Extensions/SpriteNode/CBSpriteNodeSensorExtension.swift
src/CattyTests/Embroidery/EmbroideryDSTHeaderTests.swift
src/CattyTests/Embroidery/RunningStitchPatternTests.swift
src/CattyTests/Embroidery/ZigzagStitchPatternTests.swift

https://jira.catrob.at/browse/CATTY-700
Adapt ZigZagStitch to match catroid version.
* Change the position of the stitches and adapt length:
- Before the length was from one Stitch to the next stitch on the same side, 
- now the length is from stitch to stitch (same as android)
They look similar now: 
Examples (left iOS right Android)

CATTY-700 Adapt ZigZagStitch to match Catroid

---

src/Catty/FormulaEditor/InternToExternGenerator.m

https://jira.catrob.at/browse/CATTY-670 

CATTY-670 Unsupported Element does not contain unkown XML name

---

src/Catty/DataModel/Project/Project.m
src/Catty/Defines/ProjectDefines.h
src/Catty/Extension&Delegate&Protocol/Extensions/NotificationExtension.swift
src/Catty/Firebase/FirebaseCrashlyticsReporter.swift

CATTY-666 Prevent loading of too large projects

---

src/Catty/Defines/ButtonTags.h
src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift

https://jira.catrob.at/browse/CATTY-713

CATTY-713 Fix scroll view in project detail view

---

src/Catty/BluetoothDevice/FirmataDevices/Arduino/ArduinoHelper.swift
src/Catty/BluetoothHelper/BluetoothHelper/Components/CentralManager.swift
src/Catty/BluetoothHelper/BluetoothHelper/Components/Peripheral.swift
src/Catty/BluetoothHelper/BluetoothHelper/Components/Service.swift
src/Catty/BluetoothHelper/BluetoothHelper/Helper/SimpleFutures.swift
src/Catty/BluetoothHelper/BluetoothHelper/Profiles/ProfileManager.swift
src/Catty/BluetoothHelper/BluetoothHelper/Profiles/ServiceProfile.swift
src/Catty/DataStructures/3rdParty/Stack/CBStack.swift
src/CattyTests/BluetoothDevices/BluetoothMocks/BluetoothMocks.swift
src/CattyTests/PlayerEngine/Functions/ObjectRecognition/ObjectRecognitionFunctionsTest.swift
src/CattyTests/PlayerEngine/Functions/TextRecognition/TextBlockPositionFunctionTest.swift

CATTY-730 Fix new Swiftlint warnings

---

src/Catty/ViewController/MediaLibrary/ContentViews/LibraryCategoryCollectionReusableView.swift
src/Catty/ViewController/MediaLibrary/ContentViews/LibraryCategoryCollectionReusableView.xib
src/Catty/ViewController/MediaLibrary/MediaLibraryCollectionViewDataSource.swift

changed color and size of headers
https://jira.catrob.at/browse/CATTY-708

CATTY-708 Adapt Media Library Category Header

---

src/Catty/Defines/UIDefines.swift

CATTY-716 Extend gesture area of stage menu
