src/Catty/Defines/UIDefines.h
src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Download/ProgramDetailStoreViewController.m
src/iOS_Lang/en.lproj/Localizable.strings

Adopted size of icons in CatrobatTableView (Startscreen) and tidied up
defines concerning screen sizes, added fix for pre iOS 8 devices to
check orientation (only portrait used, but for consistency reasons and
future use) and added macro to figure out the device’s screen class.

IOS-139 #done

---

src/Catty.xcodeproj/project.xcworkspace/contents.xcworkspacedata
src/Catty/App-Info.plist
src/Catty/Storyboard+XIB/iPhone.storyboard

A segue-link between a prototype (!) cell (instead of table view) and UploadViewController causes a navigation issue when compiled via Xcode7.
The reason for this issue is that the prototype cell is reused as a template cell for other menu cells that are handled by other segues.
I'm wondering why this problem does not occur in Xcode6.
This fix now addresses both versions Xcode 6 + 7.

fixes storyboard upload segue issue in Xcode7

---

src/Catty/App-Info.plist
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m

this fixes following crash:
if there are no variables and the user scrolls the picker view, then the app crashed. Now this crash is fixed with this PR.

fixes FE variable slider crash

---

src/Catty.xcodeproj/xcshareddata/xcschemes/Catty (RELEASE).xcscheme

Removed test-target from release build as it is not possible to build
it with the build option ENABLE_TESTABILITY set to „no“.

IOS-388 #done

---

src/Catty/PocketPaint/ViewController/PaintViewController.m

not sure why data used in this case instead of image.
[saveViewData isEqual:editingData] -> is equal
[self.editingImage isEqual:self.saveView.image] -> not Equal

changed comparing attributes to image instead of data

---

src/Catty/ViewController/Download/FeaturedProgramsStoreViewController.m

Quick solution, but not sure if this is the ideal solution.
Basic Problem: 
The "viewWillAppear"-Method of "BaseTableViewController (which is the base class of "FeaturedProgramsStoreViewController") was always hiding the loading indicator. Since the loading process of the resources takes longer, the loading indicator should also be visible after executing "viewWillAppear".
My solution:
Commands to hide the loading view are ignored if they come from the base class (BaseTableViewController) by introducing the "shouldHideLoadingView" property.
Other possible solutions:
- not subclassing from "BaseTableViewController"
- renaming the methods "hideLoadingView" and the property "loadingView" in "FeaturedProgramsStoreViewController" so the base class does not access them
- not calling "[super …

IOS-414 loading indicator in FeaturedProgramsStoreViewController is now appearing properly

---

src/Catty/PlayerEngine/Instructions/Sound/SpeakBrick+Instruction.swift

check if double, if yes, parse, if not, keep string
check done in Speakbrick+Instruction

#IOS-423 parsing Double value before speak

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

If the script contains no other bricks, the alert view is not displayed.

IOS-413 Alert window is displayed when deleting a script

---

src/Catty/Extension&Delegate&Protocol/Protocols/Bricks/BrickCellDataProtocol.h
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellTextData.m

* Added `enableUserInteractionAndResetHighlight` to `BrickCellDataProtocol.h` header.
* Selected brick not disabled when dimming other bricks in `disableUserInteractionAndHighlight`
* Added `UIKeyboardWillChangeFrameNotification` observer in `BrickCellTextData.h`, calling `disableUserInteractionAndHighlight` on dataDelegate if editing enabled.
@m-herold everything looks good. Could you please take a look?

[Fix][IOS-451] Keyboard Hides Note-Brick

---

src/Catty/Defines/ActionSheetAlertViewTags.h
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

The reason was that multiple `alertView`s had the same `tag`. Don't you mind if I refactor/redesign `CatrobatAlertController` to make it easier to use and less error prone?

IOS-431 application crashes when deleting scripts

---

src/Catty/PlayerEngine/Scheduler/CBBroadcastHandler.swift
src/Catty/PlayerEngine/Scheduler/CBScheduler.swift

While inspecting what is happening when infinite broadcast recursion is made, I made two changes to scheduling.
1. There was a problem with how broadcasts are handled when there are no actions active in the context that is broadcast. Essentially broadcast contexts would become active too late. I corrected this behaviour by starting those contexts more or less immediately, as they do not have to wait for anything.
2. An infinite broadcast recursion would in fact still happen with my solution proposed above. Therefore I changed the code to not actually enter the runNextInstructionGroup() method over and over again in such a case of self broadcasts, eventually running into a EXC_BAD_ACCESS error. Instead, the runNextInstructionGroup() method will be called at a later point in time, when the …

IOS-221 Crash when generating infinite broadcast recursion

---

src/Catty/PlayerEngine/Instructions/Data/ShowTextBrick+Instruction.swift

Behaviour is now equivalent to Catroid, where ShowVariable with an uninitialised user variable shows a "0" instead of nothing.

IOS-525 ShowVariableBrick - Uninitialized variable

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Extension&Delegate&Protocol/Extensions/UIBarButtonItem+InvisibleButton/UIBarButtonItem+InvisibleButton.swift
src/Catty/ViewController/BaseViewController/BaseCollectionViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SRViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/ObjectTableViewController.m
src/Catty/ViewController/Continue&New/ProgramTableViewController.m
src/Catty/ViewController/Help/HelpWebViewController.m
src/Catty/ViewController/Programs/MyProgramsViewController.m
src/Catty/ViewController/Upload/ProgramsForUploadViewController.m

- Add a UIBarButtonItem extension for convenient creation of invisible items and flex space.
- Rewrite code in order to use multiple instances of bar button items instead of only a single one added to the toolbar several times.

IOS-547 Prevent app from freezing on certain screens

---

README.md

There was a mistake in the README file: it said to write 'make init' in the 'src' directory, while it should be in the 'Catty' directory

Modified README: gave directions to call make init in parent directory

---

src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/ViewController/Programs/MyProgramsViewController.m
src/Catty/ViewController/Scene/SaveToProjectActivity.m
src/Catty/ViewController/Scene/ScenePresenterViewController.m
src/iOS_Lang/en.lproj/Localizable.strings

includes following changes
- reload program overview (program name did not get updated before i.e.)
- fix program preview image: overwriting of thumbnails when creating new previews
- rename: "Save to PocketCode" to "Set as Preview Image" for preview image functionality

IOS-626 reload program overview / overwrite program preview thumbnail

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LookImageViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m

picking media (photos) or using a photo from the camera was broken as an AlertController was trying to show itself on the UIImagePickerController which was already dismissed.
moving the corresponding code into the completion block of dismissViewControllerAnimated fixed the problem

IOS-632 Fix pick media

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Functions/Math/PowerFunction.swift
src/Catty/Settings.bundle/Root.plist
src/Catty/Setup/CatrobatSetup+Functions.swift
src/CattyTests/Formula/FormulaParserTest.m
src/CattyTests/PlayerEngine/Functions/Math/PowFunctionTest.swift

Change the .tag attribute of the power function to 'POWER' to be inline with Catroid
Also change class name: PowFunction -> PowerFunction
and filename: PowFunction.swift -> PowerFunction.swift

CATTY-58: The function POW doesn't exist in Pocket Code

---

src/Catty/PlayerEngine/Formula/FormulaManager+Interpreter.swift
src/Catty/Settings.bundle/Root.plist
src/CattyTests/PlayerEngine/AudioEngine/IntegrationTests/AudioPlayerIntegrationTests.swift
src/CattyTests/PlayerEngine/Formula/FormulaManagerInterpreterTests.swift

Ticket description: 
The evaluation of infinity differs between Catroid and Catty:
1/0 = -Double.MAX_VALUE in Catroid and "inf" in Catty
-1/0 = -Double.MAX_VALUE in Catroid and "-inf" in Catty
Added Tests for -1/0 and 1/0. Returned double.greatestFiniteMagnitude instead of "inf".

CATTY-35 Fix division by zero

---

src/Catty/Defines/NetworkDefines.swift
src/Catty/ViewController/Download/ProjectDetailStoreViewController.m

change URL of report API and add defines for min and max length of report note

CATTY-85 change report API

---

src/Catty/Views/Custom/CollectionViewCells/BrickCells/Motion/ChangeYByNBrickCell.m

Title of brick is displayed wrong. "Change Y by by ..." instead of "Change Y by ..."

CATTY-134 Change title of brick

---

src/CattyTests/PlayerEngine/AudioEngine/UnitTests/AudioPlayerTests.swift
src/CattyTests/PlayerEngine/AudioEngine/UnitTests/SpeechSynthesizerTests.swift

Removed the warnings for Nimble by replacing „free matcher functions“ by „operator overloads“.

CATTY-138 Remove warnings for Nimble

---

src/Catty/Functions/Math/AbsFunction.swift
src/Catty/Functions/Math/AsinFunction.swift
src/Catty/Functions/Math/AtanFunction.swift
src/Catty/Functions/Math/CosFunction.swift
src/Catty/Functions/Math/LnFunction.swift
src/Catty/Functions/Math/LogFunction.swift
src/Catty/Functions/Math/MaxFunction.swift
src/Catty/Functions/Math/MinFunction.swift
src/Catty/Functions/Math/ModFunction.swift
src/Catty/Functions/Math/RandFunction.swift
src/Catty/Functions/Math/RoundFunction.swift
src/Catty/Functions/Math/SinFunction.swift
src/Catty/Functions/Math/SqrtFunction.swift
src/Catty/Functions/Math/TanFunction.swift
src/CattyTests/PlayerEngine/Functions/Math/AbsFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/AsinFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/AtanFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/CosFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/LnFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/LogFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/MaxFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/MinFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/ModFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/RandFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/RoundFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/SinFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/SqrtFunctionTest.swift
src/CattyTests/PlayerEngine/Functions/Math/TanFunctionTest.swift

Change default values of math functions like in catroid
e.g. sin(0) -> sin(90) 

CATTY-143 Change math function default values

---

src/Catty/ViewController/CatrobatTableViewController/AboutPocketCodeOptionTableViewController.m

Remove the "easter egg" which causes the app to crash (implemented in CATTY-161).

CATTY-162 Remove "easter egg" for Crashlytics

---

src/Catty/DataModel/Bricks/IO/FlashBrick.m

Set the default value "on" for Turn flashlight & Turn camera brick.

CATTY-174 Change default value of camera/flashlight brick

---

.github/pull_request_template.md

Added the line "Verify that the Jira ticket is in the status Ready for Development" after "Include the name of the Jira ticket in the PR’s title". Jira Ticket: https://jira.catrob.at/browse/CATTY-180

Catty-180 Extend pull request template

---

src/Catty/ViewController/Download/ProjectDetailStoreViewController.m
src/CattyTests/FileManager/CBFileManagerTests.swift

Downloaded projects with the same name are now stored with an increasing number as if you create a project with the same name directly on your device.

CATTY-126 add increasing number to downloaded projects with same name

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Catty-Bridging-Header.h
src/Catty/Extension&Delegate&Protocol/Protocols/Bricks/BrickData/BrickListProtocol.h
src/Catty/FormulaEditor/Helper/Brick+UserVariable.m
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/CattyTests/Bricks/BrickWithUserVariableTests.swift

In Brick+UserVariable.m, the method isVarOrListBeingUsed was extended for the ReplaceItemInUserListBrick, DeleteItemOfUserListBrick and InsertItemIntoUserListBrick.
A new test class for this method was added.

CATTY-153 extend isVarOrListBeingUsed for lists

---

src/Catty/Extension&Delegate&Protocol/Extensions/UIColor+Extension/UIColor+CatrobatUIColorExtensions.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickSelectionViewController.m

I change the color of the title in the Brick selection. It was white. Now it has the same color as everywhere.
One mainfunction for the page Indicator was missing. (presentationIndexForPageViewController)

CATTY-149 Page indicator missing for Brick selection

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
src/CattyTests/FileManager/CBFileManagerTests.swift

The Problem was that the background Thread wants to call a UIViewController to present. This is not allowed. So it crashed. With dispatchQueue you can call the mainThread todo that.

CATTY-176 Crash during creating new project.

---

src/Catty/PocketPaint/Helper/ImagePicker.m

It was the same problem as in CATTY-176. BackgroundThread isn't allowed to do something with the UIView.

CATTY-189 Crash during selecting image in Paint

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryViewController.m

Since iOS13 the boundaries of the viewcontroller have changed because of it, the fault occurred

CATTY-106 Margin for BrickSelectionViewController

---

src/Catty/ViewController/Upload/LoginViewController.m
src/CattyTests/Utils/LoginViewControllerTests.swift

For non-existing users the error message "Authentication failed" is now shown such as if you login with invalid credentials.

CATTY-175 use error message authentication failed for non existing user

---

src/Catty UITests/BrickCellTests.swift
src/Catty.xcodeproj/project.pbxproj
src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellFormulaData.m

CATTY-120 change name of test
Provided more space for Parameter fields for Bricks and added a UITest. The new provided space was checked on different iPhone sizes. (from 5s onwards)
https://jira.catrob.at/browse/CATTY-120

CATTY-120 Parameter fields for Bricks

---

src/Catty UITests/ScriptCollectionView/BrickCellTests.swift
src/Catty.xcodeproj/project.pbxproj

Moved UI test named BrickCellTests to ScriptCollectionView subfolder.
Renamed function testBrickParameterSpace to testVariableBrickParameterSpace

CATTY-199: Move BrickCellTests

---

src/Catty/DataModel/Bricks/Motion/GlideToBrick.h
src/Catty/DataModel/Bricks/Motion/GlideToBrick.m

The following properties have been removed from `GlideToBrick` since they are on longer required
isInitialized
currentPoint
startingPoint
deltaX
deltaY

Catty-200 Remove deprecated properties of GlideToBrick

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Control/RepeatBrick.m
src/Catty/DataModel/Bricks/Control/RepeatUntilBrick.m
src/Catty/DataModel/Bricks/Look/SetBackgroundBrick.m
src/Catty/DataModel/Bricks/Look/SetLookBrick.m
src/Catty/DataModel/Bricks/Motion/GlideToBrick.m
src/Catty/DataModel/Bricks/Motion/PointToBrick.m
src/CattyTests/Bricks/BrickMutableCopyTests.swift
src/CattyTests/Bricks/BrickTests.swift
src/CattyTests/Bricks/GlideToBrickTests.swift
src/CattyTests/Bricks/IfLogicBeginBrickTests.swift
src/CattyTests/Bricks/PlaySoundAndWaitBrickTests.swift
src/CattyTests/Bricks/PointToBrickTests.swift
src/CattyTests/Bricks/RepeatBrickTests.swift
src/CattyTests/Bricks/RepeatUntilBrickTests.swift
src/CattyTests/Bricks/SetBackgroundBrickTests.swift
src/CattyTests/Bricks/SetLookBrickTests.swift
src/CattyTests/Bricks/WaitUntilBrickTests.swift

Added new tests to test 'mutable copy' functionality for various bricks. Removed unnecessary overriding 'mutableCopy' methods and added it where required in various subclasses of Brick. 

Catty-188: Refactor Brick tests

---

src/Catty/Functions/Text/RegularExpressionFunction.swift

Fix implicit return violations for recently changed file.

CATTY-187 Fix implicit return violations

---

src/CattyTests/Resources/ParserTests/Custom/Misc/ValidFormulaList.xml

`SpeakBrick` XML with regular expression  function added to`ValidFormulaList.xml`

CATTY-211 Add regular expression to XML

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Extension&Delegate&Protocol/Extensions/Notification/NotificationExtension.swift
src/Catty/Setup/Firebase/AppDelegateFirebaseExtension.swift
src/Catty/ViewController/Download/StoreProjectDownloader.swift
src/CattyTests/Download/StoreProjectsDownloaderTests.swift
src/CattyTests/Setup/Firebase/FirebaseCrashlyticsSetupTests.swift
src/CattyTests/Utils/NimbleMatcher.swift

Added non-fatal reports for Crashlytics when fetching projects for different possible failures. Included Unit tests for different project types (featured, most downloaded, most recent, most viewed). Added new Observer and Notification projectFetchFailure.

CATTY-195 Add non-fatal reports for Crashlytics (projects fetch)

---

.github/workflows/swiftlint.yml
src/Catty.xcodeproj/project.pbxproj
src/RunScripts/.swiftlint.yml

Since the SwiftLint is only executed with the changed files as input, this has precedence over the configuration options. Since the code should not contain any warnings at all, SwiftLint should be executed on the whole code base so that the configuration options are considered.
To make this work, the `todo` configuration should be disabled for SwiftLint and re-enabled for Xcode.

CATTY-216 Move todo warnings from SwiftLint to Xcode

---

src/CattyTests/Formula/FormulaElementTest.swift

Test added in `FormulaElementTest` class to test the `isSingleNumberFormula` method in `FormulaElement`

CATTY-202 Add test for "single number formula"

---

src/Catty/Views/Custom/CollectionViewCells/BrickCells/BrickCell.m

Make sure, that the stripes are still visible when a brick is disabled. Use the disabled stroke color of the bricks category.

CATTY-222 set stroke color of brick cell to strokeColorDisabled of category

---

src/Catty/Supporting Files/App-Info.plist

The URL for the media license is changed from `http://developer.catrobat.org/agpl_v3` to `https://developer.catrobat.org/agpl_v3` in `App-Info.plist`.

CATTY-225 Change license

---

src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.swift

Fix crash in Settings for older iOS versions. This crash occurred for iOS 10, 11 and 12, not for the most recent iOS 13.
Reason for this crash is that the outdated Bohr dependency holds an weak reference to the `destinationViewController` (https://github.com/davdroman/Bohr/blob/883ac77d59e1612e2ab549261657a6f01d42720d/Bohr/BOTableViewCell.h#L39).

CATTY-228 Fix crash in Settings for older iOS versions

---

src/Catty/Extension&Delegate&Protocol/Extensions/Notification/NotificationExtension.swift
src/Catty/Setup/Firebase/AppDelegateFirebaseExtension.swift
src/Catty/ViewController/MediaLibrary/MediaLibraryDownloader.swift
src/CattyTests/MediaLibrary/MediaLibraryDownloaderTests.swift
src/CattyTests/Setup/Firebase/FirebaseCrashlyticsSetupTests.swift

Added non-fatal reports for Crashlytics when downloading media library index or data for possible failures. Included Unit tests for different errors. Added new Observer and Notification mediaLibraryDownloadIndex and mediaLibraryDownloadData. Added FirebaseCrashlyticsSetup test.
https://jira.catrob.at/browse/CATTY-196

CATTY-196 Add non-fatal reports for Crashlytics (media library)

---

src/Catty/ViewController/Download/ChartProjects/ChartProjectStoreDataSource.swift
src/Catty/ViewController/Download/FeaturedProjects/FeaturedProjectsStoreTableDataSource.swift
src/Catty/ViewController/Download/SearchStore/SearchStoreDataSource.swift
src/Catty/ViewController/Download/StoreProjectDownloader.swift
src/CattyTests/Download/StoreProjectsDownloaderTests.swift
src/CattyTests/Mocks/StoreProjectDownloaderMock.swift

StoreProjectDownloaderProtocol is modified so that fetchProjectDetails gets a string projectId as the first parameter.

CATTY-244 Modify StoreProjectDownloaderProtocol

---

src/Catty/Helpers/Util/TableUtil.h
src/Catty/Helpers/Util/TableUtil.m
src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m

Removed the last border on the main menu screen. This line made the user maybe think that there were more list items, but there are not more.
Additional infos:
**Update 27.4.:**
I updated the PR including the requested changes. For deterring the statusbarHeight there are now 2 variables - 1 is needed to toggle between the height and 0 and the other is to determine the height at start - to not trigger the repaint every time when the rotation changes.
TL;DR:
There is a problem when starting the app in landscape to determine status bar height as the height is important for our main screen space usage. This is the reason for the properties and setters i've added. 
Full:
With removing the last border on the main screen the spacing of the buttons does not longer fit the screen exactly. After …

CATTY-90 removed last border on main menue screen

---

src/Catty/DataModel/VariablesContainer/VariablesContainer.h
src/Catty/DataModel/VariablesContainer/VariablesContainer.m
src/CattyTests/DataModel/VariablesContainerTest.swift

- isVariableOfSpriteObject
- allVariablesAndLists

CATTY-246 Remove deprecated methods for VariablesContainer

---

src/Catty/ViewController/Download/DownloadTabBarController.m

Modified the colours of the tab bar in addition to the general UI colours. Therefore white as active item felt most intuitive.

CATTY-223 MOD tab bar item color

---

src/Catty/DataModel/UserData/UserDataProtocol.swift
src/Catty/DataModel/UserData/UserList.swift
src/Catty/DataModel/UserData/UserVariable.swift
src/Catty/DataModel/VariablesContainer/VariablesContainer.h
src/Catty/DataModel/VariablesContainer/VariablesContainer.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserVariable/UserVariable+CBXMLHandler.m
src/CattyTests/DataModel/VariablesContainerTest.swift

- Made UserDataProtocol available for ObjC classes.
- Used of UserDataProtocol protocol in the VariableContainer.
- Combined the isProjectVariable and `isProjectList` again by naming it `isProjectData`.

CATTY-281 Make UserDataProtocol available for ObjC and use it in VariableContainer

---

src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.h
src/CattyTests/ViewController/FormulaEditorViewControllerTests.swift

Add regression tests for `isVarOrListBeingUsed` method of `FormulaEditor`.

CATTY-301 Add regression tests for isVarOrListBeingUsed

---

src/Catty/Helpers/Util/Util.h

Added multiple _Nonull/_Nullable statements in Util to get rid of the linter warnings

CATTY-302 FIX null/nonnull linter warnings in util

---

src/Catty/DataModel/VariablesContainer/VariablesContainer.m
src/CattyTests/DataModel/VariablesContainerTest.swift

Added two tests verifying whether two containers with one variable and one list with the same name are not equal

CATTY-306 Add additional tests for VariablesContainer

---

src/Catty/DataModel/UserData/UserList.swift
src/Catty/DataModel/UserData/UserVariable.swift

Removed the deprecated `typealias` from UserList and UserVariable class.

CATTY-310 Remove the deprecated typealias in UserList and UserVariable

---

src/Catty/DataModel/Array/SynchronizedArray.swift
src/CattyTests/DataModel/SynchronizedArrayTests.swift

Added setter and isEqual method for SynchronizedArray.

CATTY-311 Add setter and isEqual method for SynchronizedArray

---

src/Catty/DataModel/UserData/UserVariable.swift
src/Catty/DataModel/VariablesContainer/UserDataContainer.h
src/Catty/DataModel/VariablesContainer/UserDataContainer.m
src/Catty/PlayerEngine/Instructions/Data/ChangeVariableBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Data/SetVariableBrick+Instruction.swift
src/CattyTests/Bricks/WaitUntilBrickTests.swift
src/CattyTests/DataModel/UserDataContainerTest.swift
src/CattyTests/DataModel/UserVariableTests.swift

Moved the following functions from the UserDataContainer to UserVariable:
- setUserVariable
- changeVariable

CATTY-314 Move variable functions from UserDataContainer to UserVariable

---

src/Catty/DataModel/Bricks/Pen/PenDownBrick.swift
src/Catty/DataModel/Bricks/Pen/PenUpBrick.swift

- Only PenClearBrick is now visible for background and not others.

CATTY-318 Pen bricks should not be visible for Background object

---

src/Catty/DataModel/Array/SynchronizedArray.swift
src/CattyTests/DataModel/SynchronizedArrayTests.swift

Added a new extension for the SynchronizedArray.
Added remove for name function for SynchronizedArray when initialized with UserData.

CATTY-322 Add remove methods for SynchronizedArray when initialized with UserData

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController+Disable.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/CattyTests/ViewController/ScriptCollectionViewControllerDisableTests.swift

Bricks inside a nested Brick which is disabled should not be executed nor allowed to be re-enabled in the UI. This applies for:
- Repeat
- Repeat Until
- IfThen
- IfThenElse
- Forever
This PR solves the re-enabling issue not exactly like Catroid because bricks which should not be allowed to be re-enabled are and stay grey in contrast to Catroid where these bricks return to the default color but without interfering the execution (dummy bricks)

CATTY-217 Disable loops and nested Bricks

---

src/Catty/DataModel/Project/Project.h
src/Catty/DataModel/Project/Project.m
src/Catty/Extension&Delegate&Protocol/Extensions/Project+Extension/Project+CustomExtensions.m
src/Catty/Extension&Delegate&Protocol/Extensions/UserDataExtension.swift
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/Helpers/Util/Util.m
src/CattyTests/DataModel/UserDataContainerTest.swift
src/CattyTests/Project/ProjectTests.swift

Impleneted `allObjects` method in the Project class to get all the objects. Also, used the `allObjects` method in UserDataContainer instead of accessing the objectVariableList and objectListOfLists directly

CATTY-324 Get all objects and use them in UserDataContainer

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Extension&Delegate&Protocol/Extensions/GDataXMLElement/GDataXMLElement+CustomExtensions.m
src/CattyTests/Extensions/GDataXMLElementExtensionTests.swift
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml

-  Changed the comparison of the serialized XML files so that the order of the entries (entry) in the objectVariableList and objectVariableList do not matter.

CATTY-339 Compare UserDataContainer order-insensitive

---

src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLSerializerHelper.h
src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLSerializerHelper.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SetBackgroundBrick+CBXMLHandler.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SetLookBrick+CBXMLHandler.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Sound/PlaySoundAndWaitBrick+CBXMLHandler.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Sound/PlaySoundBrick+CBXMLHandler.m
src/CattyTests/Parser & Serialization/Helper/CBXMLParserHelperTests.swift

The method relativeXPathToRessourceList in CBXMLSerializerHelper.m returns a static path for every resource (look, sound).
This path should be computed dynamically, in order to work with resources, which may be introduced by new bricks.
- Created a new method to get the depth of the resource (depending on wether resource is linked to script or brick)
- The method "relativeXPathToRessourceList" (CBXMLSerializerHelper.m) now takes the depth of the resource path as an 
argument
- Added a new test

CATTY-331 Initial constuction of possible parameterization

---

src/Catty/Functions/Protocols/Function.swift
src/CattyTests/PlayerEngine/Functions/Text/JoinFunctionTest.swift

Bug fixed
- The text could be joined with the content of a list(i.e UserList) using `JOIN Function`.
- The text could be joined with the value of a variable(i.e UserVariable) using `JOIN Function`.

CATTY-315 Text can not be joined with lists

---

src/Catty/ViewController/Scene/ScenePresenterViewController+Resources.swift

Bug fixed
- Now app does not crash when resources are unavailable.

CATTY-363 App crashing with unavailable resources

---

src/Catty/PlayerEngine/Sensors/Motion/InclinationXSensor.swift
src/Catty/PlayerEngine/Sensors/Motion/InclinationYSensor.swift
src/CattyTests/PlayerEngine/Sensors/Motion/InclinationXSensorTest.swift
src/CattyTests/PlayerEngine/Sensors/Motion/InclinationYSensorTest.swift

Added landscape specific sensor behavior for Inclination Sensors. If the project is in landscape Mode the Acceleration Sensors should use the values of the opposite sensors. InclinationXSensor uses values of InclinationYSensor and vice versa.
https://jira.catrob.at/browse/CATTY-327

CATTY-327 Inclination Sensor behaviour landscape mode

---

src/Catty/PlayerEngine/Sensors/Motion/AccelerationXSensor.swift
src/Catty/PlayerEngine/Sensors/Motion/AccelerationYSensor.swift
src/CattyTests/PlayerEngine/Sensors/Motion/AccelerationXSensorTest.swift
src/CattyTests/PlayerEngine/Sensors/Motion/AccelerationYSensorTest.swift

Added landscape specific sensor behavior for Acceleration Sensors. If the project is in landscape Mode the Acceleration Sensors should use the values of the opposite sensors. _AccelerationXSensor_ uses values of _AccelerationYSensor_ and vice versa. https://jira.catrob.at/browse/CATTY-326

CATTY-326 Accelerator Sensor behaviour landscape mode

---

src/Catty/PlayerEngine/Sensors/Heading/CompassDirectionSensor.swift
src/CattyTests/PlayerEngine/Sensors/Heading/CompassDirectionSensorTest.swift

Added landscape specific sensor behavior for Compass Sensor. If the project is in landscape Mode the Compass Value should adapt by 90 degrees.

CATTY-329 Compass Direction Sensor behaviour landscape mode

---

src/Catty/PlayerEngine/Sensors/Motion/InclinationXSensor.swift
src/Catty/PlayerEngine/Sensors/Motion/InclinationYSensor.swift
src/CattyTests/PlayerEngine/Sensors/Motion/InclinationXSensorTest.swift
src/CattyTests/PlayerEngine/Sensors/Motion/InclinationYSensorTest.swift

I changed the InclinationXSensor and InclinationYSensor behaviour if the sensor is not available. There is only one standard path used to evaluate if the sensor is available. The rawValue methods (including the tests) for the opposite sensors were removed.

CATTY-373 Change default raw value sensor evaluation

---

src/Catty/Extension&Delegate&Protocol/Extensions/NSDataExtension.swift
src/CattyTests/Extensions/NSDataExtensionTests.swift

CATTY-382 Fix md5 for large NSData

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Control/BroadcastBrick.m
src/Catty/DataModel/Bricks/Control/BroadcastWaitBrick.m
src/Catty/DataModel/Project/Project.h
src/Catty/DataModel/Project/Project.m
src/Catty/DataModel/Scripts/BroadcastScript.m
src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellMessageData.m
src/CattyTests/CattyTests-Bridging-Header.h
src/CattyTests/Utils/UtilTests.swift
src/CattyTests/ViewController/ScriptCollectionViewControllerDisableTests.swift
src/CattyTests/ViewController/ScriptCollectionViewControllerTests.swift

A project variable is created, which stores all recently created messages until the project is closed, i.e. the user goes back to the main screen or the project listing screen. Once the project is reopened, only the used messages are shown.

Catty-163: New value overwrites most recent value for Broadcast

---

src/Catty/PlayerEngine/Sensors/Object/ColorSensor.swift
src/CattyTests/PlayerEngine/Sensors/Object/ColorSensorTest.swift

Bug fixed
- Now the app does not crash even if number is greater then INT-MAX

CATTY-388 SetColorBrick with a number is than INT-MAX crashes

---

src/Catty/ViewController/Upload/UploadViewController.swift
src/CattyTests/ViewController/UploadViewControllerTests.swift

- Corrected category joining so that now when trying to upload a project with more than one tags/categories then the available tags are listed as ", "-separated i.e comma without space.

CATTY-401 Uploading a project with multiple tags/categories displays categories with wrong separator

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/SegueDefines.h
src/Catty/Storyboard+XIB/iPhone.storyboard
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Continue&New/ProjectTableViewController.h
src/Catty/ViewController/Continue&New/ProjectTableViewController.m
src/Catty/ViewController/Download/ProjectDetailStoreViewController.m
src/Catty/ViewController/Projects/MyProjectsViewController.m
src/CattyTests/Extensions/UIViewControllerExtensionTests.swift
src/CattyTests/Mocks/ProjectMock.swift

Remove segues and add common loading method for Project. Move code from `shouldPerformSegue` and `prepareForSegue` to designated method to load project which will contain a more advanced logic at some point later.

CATTY-408 Add common method to open Project in UI

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Condition/WhenConditionScript+Condition.swift
src/Catty/DataModel/Scripts/Script.h
src/Catty/DataModel/Scripts/Script.m
src/Catty/DataModel/Scripts/WhenConditionScript.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Scripts/Script+CBXMLHandler.m
src/Catty/PlayerEngine/DataModel/CBScriptContext/CBScriptContext.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
src/Catty/PlayerEngine/Protocols/CBSchedulerProtocol.swift
src/Catty/PlayerEngine/Protocols/StageProtocol.swift
src/Catty/PlayerEngine/Scheduler/CBScheduler.swift
src/Catty/PlayerEngine/Stage/Stage.swift
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/ScriptCells/WhenConditionScriptCell.swift
src/CattyTests/CatrobatLanguage0.992/XMLParserTests/Unit Tests/XMLParserTests0992.swift
src/CattyTests/Mocks/StageMock.swift
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0992.xml
src/CattyTests/Scripts/WhenBackgroundChangesScriptTests.swift
src/CattyTests/Scripts/WhenConditionScriptTests.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

This Script executes all subsequent Bricks when a condition becomes true. In order to run it again later, the condition has to first become false once, and only once it becomes again true, the script will be run once more.

CATTY-15 Implement WhenConditionScript

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/PocketPaint/ViewController/PaintViewController.h
src/Catty/PocketPaint/ViewController/PaintViewController.m
src/CattyTests/Mocks/PaintViewControllerMock.swift
src/CattyTests/ViewController/PaintViewControllerTests.swift

Landscape background images are cut off by the width of the screen by default. When the background is shown cut off, the entire image can only be seen when the user zooms out by himself. Same for very long portrayed images.

CATTY-349 Scale landscape background images automatically in Paint

---

src/Catty/Helpers/BrickHelpers/CameraPreviewHandler.h
src/Catty/Helpers/BrickHelpers/CameraPreviewHandler.m
src/Catty/PlayerEngine/Sensors/Camera/FaceDetectionManager.swift
src/CattyTests/Bricks/ChooseCameraBrickTests.swift

When the `ChooseCameraBrick` is used inside the `WhenTouchDownScript` it becomes impossible to open the menu and therefore to close the game. (See [CATTY-49](https://jira.catrob.at/browse/CATTY-49) )
Turns out this was due to the camera setup being executed on (and therefore blocking) the UI Thread. This PR changes this behaviour.

CATTY-49 Project can't be closed

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Extension&Delegate&Protocol/Extensions/NSMutableArrayExtension.swift
src/Catty/ViewController/Continue&New/SceneTableViewController.m
src/Catty/ViewController/Projects/MyProjectsViewController.m
src/CattyTests/Extensions/NSMutableArrayExtensionTests.swift

Converted the NSMutable Array Extension from Objective-C to swift and added a Unit test to verify the behavior.

CATTY-256 Convert NSMutableArray to Swift

---

src/Catty/DataModel/Bricks/Motion/GoToBrick.m

When copying a "Go to [object]" Brick, the copied Brick points to a different object. Instead, the copied Brick should point to the same object.

CATTY-414 Fix Copy "Go to [object]" Brick

---

src/Catty/PocketPaint/Tools/MirrorRotationZoomTool.m

Fixed the brush tool behaviour after rotating an image.

CATTY-194 fix unexpected brush tool behaviour

---

src/Catty/FormulaEditor/InternToExternGenerator.m
src/CattyTests/Formula/InternFormulaTest.m

When input number is greater than 15 digits de conversion was wrong - bypassed it and added a test for that case.

CATTY-157 fixed parameter input problem with long numbers

---

src/CattyTests/ViewController/PaintViewControllerTests.swift

The testSetupZoomCenterPosition test inside the PaintViewControllerTests.swift file is failing when executing it with an iPhone SE 2nd gen.

CATTY-425 PaintViewControllerTests failing with iPhone SE 2nd Gen

---

Jenkinsfile

The "The file couldn’t be saved." error is related to the temporary Carthage cache. In order to solve this problem, the Carthage temporary items need to be removed therefore a new stage called "Clear Carthage temporary items" was added.
This new stage should now remove the temporary Carthage cache on every Jenkins test start.

CATTY-434 Fix for Jenkins failing with The file couldn’t be saved. error

---

Jenkinsfile
src/fastlane/Fastfile

Collate reports at multi_scan directly.

CATTY-447 Fix lane "test_reports"

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

Since the user assumes that the project is saved anyways, the "saved" notification should be removed when reordering Bricks.

CATTY-429 Removed *saved* notification when reordering Bricks

---

src/Catty/DataModel/Array/SynchronizedArray.swift
src/Catty/PlayerEngine/Scheduler/CBScheduler.swift
src/CattyTests/Bricks/WaitBrickTests.swift
src/CattyTests/DataModel/SynchronizedArrayTests.swift

Replaced _activeTimers and timerQueue with a SynchronizedArray of ExtendedTimer.

CATTY-360 Use SynchronizedArray in CBScheduler

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickManager/BrickInsertManager.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

Since the user assumes that the project is saved anyways, the "saved" notification should be removed when adding new and deleting existing Bricks.

CATTY-444 Remove "saved" notification when adding and deleting Bricks

---

src/CattyTests/DataModel/SoundTest.swift

Add tests for the Sound class to the the following methods (LookTest.swift):
initWithName
mutableCopyWithContext
isEqualToSound

CATTY-455 Add tests for sounds

---

src/CattyTests/DataModel/SoundTest.swift

Test shows warning: Initialization of immutable value 'bundle' was never used; consider replacing with assignment to '_' or removing it

CATTY-465 Remove Swift Compiler Warning For SoundTest

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/UIDefines.h
src/Catty/Defines/UIDefines.swift
src/Catty/Storyboard+XIB/iPhone.storyboard
src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
src/Catty/ViewController/Download/ChartProjects/ChartProjectCell.swift
src/Catty/ViewController/Download/SearchStore/SearchStoreCell.swift
src/Catty/ViewController/Projects/MyProjectsViewController.m
src/Catty/Views/Custom/TableView/Cell/RoundedImageView.swift

The preview images for Objects and Looks (as well as Backgrounds) should be rounded in the same way as the preview images for projects

CATTY-440 Round border for Looks and Object Preview Images

---

.github/workflows/swiftlint.yml

SwiftLint warnings and errors are not displayed next to the "Files changed" tab on GitHub anymore. This has been fixed in https://github.com/norio-nomura/action-swiftlint/pull/36.

CATTY-475 Fix GitHub annotations for SwiftLint

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryViewController.m

Fix iOS 10 insets for BrickCategoryViewController

CATTY-482 Fix iOS 10 insets for BrickCategoryViewController

---

src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/LookBricks/AskBrick+CBXMLHandler.swift
src/Catty/PlayerEngine/Instructions/Look/AskBrick+Instruction.swift
src/CattyTests/Bricks/AskBrickTests.swift

If you execute the askBrick without a userVariable, Catty crashes.

CATTY-489 Ask Brick crashes on empty userVariable

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/ViewController/BluetoothDeviceSelection/BluetoothDevicesTableViewController.swift
src/Catty/ViewController/Stage/StagePresenterViewControllerResourcesExtension.swift
src/CattyTests/Mocks/StagePresenterViewControllerMock.swift
src/CattyTests/ViewController/Stage/StagePresenterViewControllerTests.swift

Crashlytics reports several crashes in StagePresenterViewControllerResourcesExtension line #34. The force unwrapping could be a potential cause for this crash. Thus, remove the force-unwrapping and display an error message in case the project can not be loaded (use kLocalizedInvalidZip). 
Another potential error source could be that the formula manager and thus location managers and similar are initialized not from the main thread which is bad practice according to Apple. Hence, move the formulaManager initialization and the readyToStart variable down into the main thread dispatch queue.

CATTY-493 Fix potential bugs in StagePresenterViewController

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Extension&Delegate&Protocol/Extensions/URLSessionMultipartExtension.swift
src/Catty/Store/StoreProjectUploader.swift
src/CattyTests/URLSessionMultipartExtensionTests.swift

Add an extension for the URLSession (Catty/Extensions.../Extensions/URLSessionMultipartExtension.swift) providing an multipart/form-data upload task:
open func multipartUploadTask(with url: URL, from formData: [String: String]?, attachmentData: [String: Data]?, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionUploadTask

CATTY-251 Extension for URLSession

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Look/SetLookByIndexBrick.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/LookBricks/SetLookByIndexBrick+CBXMLHandler.swift
src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/SetLookByIndexBrick+Instruction.swift
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SetLookByIndexBrickCell.swift
src/CattyTests/Bricks/SetLookByIndexBrickTests.swift
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0992.xml
src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0993.xml
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

Implemented a new Brick called "SetLookByIndexBrick". This Brick changes the Look of the current SpriteObject to a look identified by a given number.

CATTY-439 Implement SetLookByIndexBrick

---

src/Catty/DataModel/Formula/FormulaElement.h
src/Catty/DataModel/Formula/FormulaElement.m
src/Catty/PlayerEngine/Formula/FormulaManager+Interpreter.swift
src/CattyTests/Parser & Serialization/CatrobatLanguage0.93/Unit Tests/XMLParserFormulaTests093.swift
src/CattyTests/PlayerEngine/Formula/FormulaManagerInterpreterTests.swift
src/CattyTests/Resources/ParserTests/Custom/Misc/ValidFormulaList.xml

Certain projects contain formula types which are not supported by Catty yet (e.g., the collision detection which will be introduced soon). As a result Catty crashes in FormulaManager+Interpreter.swift line 175.
Reason for this is that unknown formulas are parsed with an invalid type (-1), see elementTypeForString. Instead of returning the invalid value -1, a new ElementType should be created and called UNKNOWN.

CATTY-499 Unknown formula type leads to crash

---

src/Catty/Parser&Serialializer/New Parser & Serializer/Serializer/CBXMLSerializer.m
src/CattyTests/Parser & Serialization/CatrobatLanguage0.993/XMLSerializerTests/XMLSerializerTests.swift

When starting Catty in Xcode, the content of the XML file to be parsed is output on the console.

CATTY-500 Do not output content of XML file while parsing

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Store/StoreProjectUploader.swift
src/CattyTests/Store/Upload/Fixture/StoreProjectUpload.uploadProject.fail.invalidToken.json
src/CattyTests/Store/Upload/StoreProjectUploaderTests.swift

In the StoreProjectUploader, .authenticationFailed should also be returned in the case of status code 403 (and also in the current case of 401). Do not forget to add tests and also a new DVR fixture.

CATTY-505 Uploading project with invalid token

---

src/Catty/Embroidery/EmbroideryStream.swift
src/CattyTests/Embroidery/EmbroideryDSTServiceTests.swift
src/CattyTests/Embroidery/EmbroideryStreamTests.swift

The EmbroideryStream should get a new initializer which allows to merge several EmbroideryStreams into one:
init(streams: [EmbroideryStream])
Every stitch in each stream should be added using the (private) appendStitch method, thus without interpolation. After each EmbroideryStream there should be a color change.
The example color_change.dst file (already included in Catty) was created with the following input (see this example project for details):
EmbroideryStream(stitch (0, 0), stitch(250, 0))
EmbroideryStream(stitch (0, 0), stitch(0, 250))
Add unit tests and integration tests (i.e., using the color_change.dst file) and ensure that a color change happens between the two streams.

CATTY-506 Merge EmbroideryStreams

---

src/Catty/BluetoothHelper/BluetoothHelper/Components/Peripheral.swift
src/Catty/Helpers/Firmata/Firmata.swift
src/Catty/PlayerEngine/CBCustomTypes.swift

Remove the deprecated TODO comments in Firmata.swift and CBCustomerTypes.swift, as well as the irrelevant FIXME comments of Peripheral.swift.

CATTY-516 Remove deprecated TODO and FIXME

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/PocketPaint/Helper/PaintImageView.swift
src/Catty/PocketPaint/Tools/DrawTool.m
src/Catty/PocketPaint/Tools/FillTool.m
src/Catty/PocketPaint/Tools/LineTool.m
src/Catty/PocketPaint/Tools/MirrorRotationZoomTool.m
src/Catty/PocketPaint/Tools/PipetteTool.m
src/Catty/PocketPaint/UndoManager/UndoManager.m
src/Catty/PocketPaint/ViewController/PaintViewController.h
src/Catty/PocketPaint/ViewController/PaintViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.h
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
src/CattyTests/Paint/PaintImageViewTests.swift
src/CattyUITests/CreateProjectTests.swift
src/CattyUITests/Extensions/XCTestCaseExtension.swift
src/CattyUITests/LooksTVCTests.swift
src/CattyUITests/ScriptCollectionView/BrickCellTests.swift

After drawing an image in Paint, the user is asked whether he/she wants to save the changes. This alert should appear BEFORE the view controller is changed, i.e. while still being in Paint. When the user presses "Cancel" then the user should still see the Paint with all his/her drawings

CATTY-459 Save changes in Paint

---

src/CattyTests/Formula/FormulaTest.swift

Add missing tests for the mutable copy functionality of the Formula. Add those tests to FormulaTest.swift and make sure to test it with a formula tree having several levels of left and right children.

CATTY-512 Add missing tests for Formula mutableCopy

---

src/CattyUITests/FormulaEditorTests.swift

Fix occasional testFormulaEditorSave failure by increasing the wait time.

CATTY-528 Fix occasional testFormulaEditorSave failure

---

src/CattyTests/Bricks/SetXBrickTests.swift
src/CattyTests/Bricks/SetYBrickTests.swift
src/CattyTests/Bricks/ShowBrickTests.swift
src/CattyTests/Bricks/ShowTextBrickTests.swift
src/CattyTests/Bricks/TurnLeftBrickTests.swift
src/CattyTests/Bricks/TurnRightBrickTests.swift
src/CattyTests/Bricks/VibrationBrickTests.swift
src/CattyTests/Bricks/WaitBrickTests.swift

The mutableCopyWithContext method of the Bricks create a deep copy of a Brick which is used when copying a Brick in the "Script view" in Pocket Code.
Add a test for this method for the following Bricks (have a look at the RepeatBrickTests class):
- SetXBrick
- SetYBrick
- ShowTextBrick
- ShowBrick
- TurnLeftBrick
- TurnRightBrick
- VibrationBrick
- WaitBrick

CATTY-207 Add tests for mutable copy (part 4)

---

src/Catty/DataModel/Project/Project.m
src/Catty/Defines/UIDefines.h
src/Catty/Extension&Delegate&Protocol/Extensions/NotificationExtension.swift
src/Catty/IO/FileManager/CBFileManager.m
src/Catty/ViewController/BaseViewController/BaseTableViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController.m
src/Catty/ViewController/Upload/UploadViewController.swift

removed unused Notification Defines and moved used Defines to Notification Extension

CATTY-476 remove unused notification name defines, move used defines to NotificationExtension

---

src/Catty/PlayerEngine/Sensors/Object/RotationSensor.swift
src/CattyTests/PlayerEngine/Sensors/Object/RotationSensorTest.swift

App crash when computing "direction" in FE. Reproduce by adding the "direction" sensor and pressing "compute" in the Formula Editor.

CATTY-518: App crash when computing "direction" in FE

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m

Delete the brickSelected notification in the ScriptCollectionViewController since it is already fired in the BrickCategoryViewController.

CATTY-495 Brick selected notification fired twice

---

src/CattyTests/PlayerEngine/AudioEngine/IntegrationTests/AudioPlayerIntegrationTests.swift

Adapt occasionally failing AudioPlayerIntegrationTests
Change assertion values to highest lower-bound.

CATTY-131 AudioPlayerIntegrationTests fail occasionally

---

src/Catty/Embroidery/EmbroideryDSTService.swift
src/Catty/Embroidery/EmbroideryStream.swift
src/CattyTests/Embroidery/EmbroideryDSTServiceTests.swift
src/CattyTests/Embroidery/EmbroideryStreamTests.swift

Currently merging two `EmbroideryStream`s with too much distance between them causes the app to crash wenn the resulting Stream is converted to a DST-file.
This PR fixes this issue  

CATTY-521 Merging of EmbroideryStreams crashes

---

src/Catty/PocketPaint/UndoManager/UndoManager.m
src/Catty/Supporting Files/Catty-Bridging-Header.h
src/CattyTests/Mocks/PaintViewControllerMock.swift
src/CattyTests/ViewController/PaintViewControllerTests.swift

Image is not on the correct position anymore, after rotate and undo this action. (PocketPaint, not Brick)

CATTY-533 UnDo a rotation of an image, it is not on the correct position

---

src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/ProjectDetailStoreViewControllerReportExtension.swift
src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.h
src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.m
src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift
src/CattyTests/Extensions/ProjectDetailStoreViewControllerExtensionTests.swift

https://jira.catrob.at/browse/CATTY-530
The following methods have been moved from ProjectDetailStoreViewController.m to ProjectDetailStoreViewControllerExtension.swift:
loadProject
createViewForProject
And the following method has been removed: reloadWithProject

CATTY-530 Modify Swift extension for ProjectDetailStoreViewController

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m

If you are using the app for the first time and want to set a background, the app crashes if you give permission for the photo library.
Important: This happens only on the actual develop branch not on the latest Release.

Catty-532 App crash -> allow to use photo library

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Category/BrickCategory.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryOverviewController.swift
src/CattyTests/Bricks/BrickCategoryTest.swift
src/CattyTests/Setup/CatrobatSetupTests.swift
src/CattyTests/ViewController/BrickCategoryOverviewControllerTests.swift
src/CattyTests/ViewController/BrickCategoryViewControllerTests.swift

When opening a project with a Brick of a currently disabled extension (e.g., Arduino or later also Embroidery), the Brick is displayed in black. Instead the Brick should always be displayed in its actual color.
Probably that's because the category is not added at the BrickSetup. From a user point of view, this behavior should not change, meaning the category should be disabled for the user (maybe added but hidden?).

CATTY-514 Wrong Brick color for Bricks of a disabled extensions

---

src/Catty/PocketPaint/Tools/MirrorRotationZoomTool.m
src/CattyTests/CattyTests-Bridging-Header.h
src/CattyTests/Mocks/PaintViewControllerMock.swift
src/CattyTests/ViewController/PaintViewControllerTests.swift

When rotating a background image e.g. 4 times so that it is aligned as it was before, it can be clearly seen that there is a huge difference in resolution. When using the rotated image as background afterwards, it can also be seen a difference because the background is much smaller by default.

CATTY-376 Image resolution worsens after rotating the background image

---

src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellFormulaData.m
src/Catty/Views/Custom/CollectionViewCells/BrickCells/BrickCell.h
src/Catty/Views/Custom/CollectionViewCells/BrickCells/BrickCell.m
src/CattyTests/Views/BrickCells/Data/BrickCellFormulaDataTests.swift

To make better use of the space, the formula fields should have a variable width, meaning that they should use up all the space which (a) is available and (b) they need in order to display as many characters as possible. The limit of course is the very right of the screen or, in case there are several parameters, the next parameter. In the event of several formula parameters per line, then this should be equally distributed between those parameters.
This should not only apply to the above Brick but to all Bricks having Formulas. In case this is too much change at once, we can also split this story up for every Brick category (i.e., in that case stick only to the Look category).

CATTY-445 Variable width for Formula fields

---

src/Catty.xcodeproj/project.pbxproj

Remove duplicate build compile warning for "FormulaEditorViewControllerInputExtension"

CATTY-544 Remove duplicate build compile warning

---

src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/CatrobatTableViewControllerExtension.swift
src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/ProjectDetailStoreViewControllerDownloadExtension.swift
src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/ProjectDetailStoreViewControllerReportExtension.swift
src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/UIViewControllerExtension.swift
src/Catty/Helpers/Bluetooth/BluetoothService.swift
src/Catty/Helpers/Util/Util.h
src/Catty/Helpers/Util/Util.m
src/Catty/Helpers/Util/Util.swift
src/Catty/ViewController/BluetoothDeviceSelection/BluetoothDevicesTableViewController.swift
src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.swift
src/Catty/ViewController/PrivacyPolicy/PrivacyPolicyViewController.swift
src/Catty/ViewController/Stage/StagePresenterViewControllerResourcesExtension.swift
src/Catty/ViewController/Upload/UploadViewController.swift

CATTY-523 Convert Util methods to Swift 2/3
The following methods of Util.m (and Util.h) have been converted Swift (Util.swift):
alertWithText
alertWithTitle
defaultAlertForNetworkError
defaultAlertForUnknownError
showNotificationWithMessage
showNotificationForSaveAction

CATTY-523 Convert Util methods to Swift 2/3

---

src/Catty/DataModel/Project/Project.h
src/Catty/DataModel/Project/Project.m
src/Catty/IO/ProjectManager.swift
src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.m
src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift
src/CattyTests/FileManager/ProjectManagerTests.swift
src/CattyTests/Project/ProjectTests.swift

Implements https://jira.catrob.at/browse/CATTY-537
Instead of opening the most recent, it was agreed to let the user choose the project to open if multiple are present on the device (see ticket).
Code was moved to Swift Extension to avoid writing any new ObjC code.

CATTY-537 Open multiple downloaded project from Store

---

src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m

When opening the Formula Editor for a Brick with (at least) two formulas, and switching the formula by tapping on another formula, a "changes saved" notification appears. This notification should be removed.
Also remove the "changes discarded" notification and the force change gesture with double-tap which is not working properly and which is not needed anymore (showChangesDiscardedView and forceChange parameter of changeBrickCellFormulaData).

CATTY-576 Remove notifications in Formula Editor

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/ViewController/Stage/StagePresenterViewControllerShareExtension.swift
src/CattyTests/Mocks/EmbroideryServiceMock.swift
src/CattyTests/PlayerEngine/Mocks/SpriteObjectMock.swift
src/CattyTests/ViewController/Stage/StagePresenterViewControllerTests.swift

Merging EmbroideryStreams can lead to lost stitches due to conversion into color change stitches.
Furthermore the exact behavior of color changes between merged streams is not well defined.

CATTY-578 Incorrect color change when merging EmbroideryStreams

---

src/Catty.xcodeproj/project.pbxproj
src/CattyTests/BluetoothDevices/Arduino/ArduinoTests.swift
src/CattyTests/BluetoothDevices/BluetoothMocks/BluetoothMocks.swift
src/CattyTests/BluetoothDevices/Phiro/PhiroDeviceTest.swift
src/CattyTests/Firebase/FirebaseCrashlyticsReporterTests.swift
src/CattyTests/Mocks/CrashlyticsMock.swift
src/CattyTests/PlayerEngine/AudioEngine/Helpers/AudioEngineAbstractTest.swift
src/CattyTests/TestHelpers/ForceInit.h
src/CattyTests/TestHelpers/ForceInit.m

Implements https://jira.catrob.at/browse/CATTY-574
Xcode 12.5 is more strict when checking initializers marked as NS_UNAVAILABLE, thus some old hacks for creating Mock objects started to produce errors. This PR contains some new hacks that make it work again.

CATTY-574 Xcode 12.5 support

---

src/CattyUITests/FormulaEditorKeyboardTests.swift
src/fastlane/Fastfile

Fail fastlane build on test error and fix failing test for Xcode 12.5.

CATTY-585 Fail fastlane build on test error

---

src/Catty/ViewController/Stage/StagePresenterSideMenuView.swift
src/CattyTests/ViewController/Stage/StagePresenterSideMenuViewTests.swift

Currently the "Maximize" icon is permanently shown in landscape mode. Hide the "Maximize" icon if the project's resolution is the same as the current device's resolution.
Do not forget to add tests.

CATTY-557 Hide Maximize icon in sidebar for landscape mode

---

src/Catty/PocketPaint/Tools/LineTool.m

The last point should just get saved if the recognizer recognized more than zero touches. I was unable to reproduce the BUG afterwards, but hence it occurred occasionally before it would be great to additionally manual test the PR's version.
https://jira.catrob.at/browse/CATTY-579

CATTY-579 Crash while using line tool

---

src/Catty/Supporting Files/Catty-Bridging-Header.h
src/Catty/ViewController/MediaLibrary/MediaLibraryViewController.swift

When adding a sound from the media library, sounds can be played while being in the media library. That should not be possible when having the mute switch on. Instead, the same alert should be displayed, like when trying to play sounds from within the "SoundsTableViewController".

 CATTY-588-Play-media-library-sound-while-muted

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Defines/UIDefines.h
src/Catty/Defines/UIDefines.swift
src/Catty/Extension&Delegate&Protocol/Extensions/UIColorExtension.swift
src/Catty/Helpers/Util/Util.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryViewController.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickManager/BrickManager.m
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickManager/RecentlyUsedBricksManager.swift
src/CattyTests/Bricks/BrickManager/RecentlyUsedBricksManagerTests.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

Instead of the currently available "Frequently used" Bricks, this feature should be named "Recently used" Bricks and display the last used 10 Bricks. 10 should be a variable which can be defined in the UIDefines.swift.
The recently used Bricks should be persisted and be available on a cross-project manner. Thus, they need to be persisted. Come up with a new and clean implementation in Swift and add tests.
In case a user installs Catty as a new app, the "Recently used" category should not be displayed (like the "Frequently used" category)

CATTY-543-PPPP-Recently-used-Bricks

---

src/CattyTests/XML/Parser/XMLParserBlackBoxTests.swift
src/CattyTests/XML/Serializer/XMLSerializerBlackBoxTests.swift

!! First merge #1664 , then change tests to CBL 0994 files !!
Added test for the "EscapingChars" XML files to:
- XMLParserBlackboxTests
- XMLSerializerBlackboxTests

CATTY-603 Add XML tests for EscapingChars

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/Helpers/ThemesHelper/ThemesHelper.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController+MediaLibrary.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController+SelectFile.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController.m
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

In addition to adding sounds via the "Pocket Code Recorder" and "Media library", sounds should also be imported from the Files app on the phone (e.g., from the download folder).
Add a new item called "Select file" below "Media library" and let the user select a sound from the device using a UIDocumentPickerViewController or similar. Only the following file extensions should be allowed:
-wav
-mpga
-mp3

CATTY-508-Import-sound-from-files

---

src/Catty/PlayerEngine/Formula/FormulaManager+Editor.swift
src/CattyTests/PlayerEngine/Formula/FormulaManagerTests.swift

When the project has only a Background object and when clicking on the properties section the Formula Manager the collision formula removes the background object and has a empty objectlist that leads to crash. Added a check to not iterate over an empty list

CATTY-611 CollisionFunction in FormulaEditor leads to crash

---

src/Catty/DataModel/Scripts/WhenConditionScript.swift
src/CattyTests/Scripts/WhenConditionScriptTests.swift

Enables the immediate execution of the WhenConditionScript and provides unit test. For subsequent executions the condition needs to be false in order to run a script again.

CATTY-624 WhenConditionScript not working for first execution

---

src/Catty/ViewController/BluetoothDeviceSelection/BluetoothDevicesTableViewController.swift

StagePresenterViewController was pushed onto NavigationController of BluetoothPopupVC, hence stopping the project lead to being trapped in the selection screen. Now, the presenting view controller (Navigation Controller of BluetoothPopupVC) gets dismissed before pushing the StagePresenterViewController.

CATTY-546 Select Arduino device screen can not be closed

---

src/Catty/PlayerEngine/Sensors/Phiro/PhiroBottomLeftSensor.swift
src/Catty/PlayerEngine/Sensors/Phiro/PhiroBottomRightSensor.swift
src/Catty/PlayerEngine/Sensors/Phiro/PhiroFrontLeftSensor.swift
src/Catty/PlayerEngine/Sensors/Phiro/PhiroFrontRightSensor.swift
src/Catty/PlayerEngine/Sensors/Phiro/PhiroSideLeftSensor.swift
src/Catty/PlayerEngine/Sensors/Phiro/PhiroSideRightSensor.swift
src/CattyTests/PlayerEngine/Sensors/Phiro/PhiroSensorTest.swift

Add a test to PhiroSensorTest for each of the following sensors which should test the rawValue method:
- PhiroSideLeftSensor
- PhiroSideRightSensor
- PhiroFrontLeftSensor
- PhiroFrontRightSensor
- PhiroBottomLeftSensor
- PhiroBottomRightSensor
These methods should verify that the BluetoothService/Phirodevice is called properly with the right pin values. Create test doubles for the PhiroDevice and inject that to the BluetoothService (phiro).
Do not forget to remove the TODO comment in the PhiroSensorTest.

CATTY-452 Add missing tests for PhiroSensorTest

---

src/Catty/DataModel/Bricks/Look/SetBackgroundByIndexBrick.swift
src/Catty/DataModel/Bricks/Look/SetLookByIndexBrick.swift
src/Catty/PlayerEngine/Instructions/Look/SetBackgroundByIndexBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/SetLookByIndexBrick+Instruction.swift
src/Catty/XML/XMLHandler/Bricks/LookBricks/SetBackgroundByIndexBrick+CBXMLHandler.swift
src/Catty/XML/XMLHandler/Bricks/LookBricks/SetLookByIndexBrick+CBXMLHandler.swift

The formula in those two Bricks is optional, however the Brick can not exist without such a formula. Therefore, refactor the two Bricks so that their formula is non-optional and remove any force-unwrappings.

CATTY-548 Refactor SetLookByIndex- and SetBackgroundByIndexBrick

---

src/Catty/ViewController/Upload/UploadCategoryViewController.swift
src/Catty/ViewController/Upload/UploadViewController.swift
src/CattyTests/ViewController/UploadViewControllerTests.swift

https://jira.catrob.at/browse/CATTY-632
The issue was that we were using ", " as tag separators, while Catroid & the Share expect "," without a space

CATTY-632 Uploading project with multiple categories

---

src/Catty/Extension&Delegate&Protocol/Extensions/DoubleExtension.swift
src/Catty/PlayerEngine/AudioEngine/AudioEngineHelper.swift
src/Catty/PlayerEngine/Instructions/Look/AskBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/SayBubbleBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/SayForBubbleBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/ThinkBubbleBrick+Instruction.swift
src/Catty/PlayerEngine/Instructions/Look/ThinkForBubbleBrick+Instruction.swift

Instead of using displayString from Formula now the formula gets evaluated.
In addition a minor refactor of Double to String conversion is included. 

CATTY-629 Formula not evaluated for Ask Brick

---

src/Catty/ViewController/MediaLibrary/MediaLibraryViewController.swift

Removes bottom bar when pushing MediaLibraryViewController and adds it when popping.

CATTY-640 Remove bottom bar at media library

---

src/Catty/PlayerEngine/Sensors/Camera/FaceDetectionManager.swift

The function `FormulaEditorViewController.showComputeDialog(_:)` has a long computing time that is caused by calling `setup` on the _formulaManager_. Calling the constructor of _CIDetector_ and starting the _session_ are causing this brief freeze. Running them asynchronously fixes this behavior.

CATTY-519 Computing values for face detection freezes UI

---

src/Gemfile.lock
src/fastlane/Pluginfile

- Fix fastlane github action by removing the trainer plugin from fastlane
- Using deprecated Crowdin version was not the cause of the error
https://jira.catrob.at/browse/CATTY-639

Fix fastlane migration error

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/DataModel/Bricks/Embroidery/StopCurrentStitchBrick.swift
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/PlayerEngine/Instructions/Embroidery/StopCurrentStitchBrick+Instruction.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Bricks.swift
src/Catty/Views/Custom/CollectionViewCells/BrickCells/Embroidery/StopCurrentStitchBrickCell.swift
src/Catty/XML/XMLHandler/Bricks/Embroidery/StopCurrentStitchBrick+CBXMLHandler.swift
src/CattyTests/Bricks/StopCurrentStitchBrickTests.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

This PR adds a Brick to stop currently running stitching patterns such as the `RunningStitchPattern`.

CATTY-625 Stop current stitch brick

---

src/Catty.xcodeproj/project.pbxproj
src/Catty.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
src/Catty/PlayerEngine/AudioEngine/AudioPlayer.swift
src/CattyTests/PlayerEngine/AudioEngine/Mocks/AudioEngineFingerprintingStub.swift
src/CattyTests/PlayerEngine/AudioEngine/UnitTests/AudioPlayerTests.swift

Update AudioKit to Version 5.3.1 and check whether all Sound- and all Speech-Bricks are still working correctly (including volume change, mute, etc).

CATTY-638 Update AudioKit to Version 5.3.1

---

src/Catty/Helpers/BrickHelpers/BubbleBrickHelper.swift
src/Catty/PlayerEngine/Stage/Constraints/SpriteBubbleConstraint.swift
src/CattyTests/PlayerEngine/Scene/Constraints/SpriteBubbleConstraintsTests.swift

https://jira.catrob.at/browse/CATTY-502
Speaking and thinking bubbles are placed next to the visible part of the look (ignoring transparent parts of the bounding box). 
In addition, the behaviour when sprites touch or move beyond the edge of the screen has been adapted to match Catroid's behaviour. 
Also removes unit tests for Y-axis collision handling, since Y-axis collisions are ignored now. 

CATTY-502 Incorrect placement of Say/Think bubbles

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/Defines/LanguageTranslationDefines.h
src/Catty/Defines/LanguageTranslationDefinesSwift.swift
src/Catty/PlayerEngine/Sensors/Camera/FaceDetectedSensor.swift
src/Catty/PlayerEngine/Sensors/Camera/FaceDetectionManager.swift
src/Catty/PlayerEngine/Sensors/Camera/FacePositionYSensor.swift
src/Catty/PlayerEngine/Sensors/Camera/FaceSizeSensor.swift
src/Catty/PlayerEngine/Sensors/Camera/SecondFaceDetectedSensor.swift
src/Catty/PlayerEngine/Sensors/Camera/SecondFacePositionXSensor.swift
src/Catty/PlayerEngine/Sensors/Camera/SecondFacePositionYSensor.swift
src/Catty/PlayerEngine/Sensors/Camera/SecondFaceSizeSensor.swift
src/Catty/Resources/Localization/en.lproj/Localizable.strings
src/Catty/Setup/CatrobatSetup+Sensors.swift
src/Catty/XML/XMLHandler/Formula/FormulaElement+CBXMLHandler.m
src/CattyTests/Mocks/VNFaceObservationMock.swift
src/CattyTests/PlayerEngine/Sensors/Camera/FaceDetectionManagerTest.swift
src/CattyTests/PlayerEngine/Sensors/Camera/FaceDetectionSensorTest.swift
src/CattyTests/PlayerEngine/Sensors/Camera/FacePositionXSensorTest.swift
src/CattyTests/PlayerEngine/Sensors/Camera/FacePositionYSensorTest.swift
src/CattyTests/PlayerEngine/Sensors/Camera/FaceSizeSensorTest.swift
src/CattyTests/PlayerEngine/Sensors/Mocks/FaceDetectionManagerMock.swift
src/CattyTests/Resources/ParserTests/Custom/Sensors/BackwardsCompatibleFaceDetectionSensors.xml
src/CattyTests/Resources/ParserTests/Custom/Sensors/FaceDetectionSensors.xml
src/CattyTests/XML/Parser/CatrobatLanguage0.9993/XMLParserTests09993.swift
src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift

https://jira.catrob.at/browse/CATTY-651
- refactor existing face detection from CoreImage to Vision framework
- change XML Tags and sensor names from previous single face detection and make it backwards compatible
- add sensors for second face detection

CATTY-651 Enable face detection for two faces

---

src/Catty/ViewController/Stage/StagePresenterViewController.m

https://jira.catrob.at/browse/CATTY-664
`stopCamera` was called from the background thread queue `DISPATCH_QUEUE_PRIORITY_DEFAULT` although it should have been called from the main thread. 

CATTY-664 Fix crash due to CameraBrick

---

src/Catty/FormulaEditor/ViewController/FormulaEditorSectionViewController/CreateVariableOrListViewController.swift
src/Catty/ViewController/CatrobatTableViewController/FormTableViewController/FormItem.swift
src/Catty/ViewController/CatrobatTableViewController/FormTableViewController/FormTextFieldTableViewCell.swift
src/CattyUITests/ScriptCollectionView/BrickCellPickerViewerTest.swift

(https://jira.catrob.at/browse/CATTY-657)
When creating new variables or lists the focus should be inside the variable name field
For testing: Add a new data brick to any script and create a new variable. Focus should be in the text field

CATTY-657 Focus on variable name

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/ViewController/BaseViewController/BaseCollectionViewController.m
src/Catty/ViewController/BaseViewController/BaseTableViewController.h
src/Catty/ViewController/BaseViewController/BaseTableViewController.m
src/Catty/ViewController/Stage/StagePresenterViewControllerResourcesExtension.swift
src/CattyTests/Mocks/BaseTableViewControllerMock.swift
src/CattyTests/ViewController/BaseCollectionViewControllerTests.swift
src/CattyTests/ViewController/Stage/StagePresenterViewControllerTests.swift
src/CattyUITests/ScenePresenterVCTests.swift

Displays a loading screen when a project is started, until the project serialization has finished. 

CATTY-637 Starting a project which has not been saved yet

---

src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryOverviewController.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryViewController.m

Check if all references of (tint)colors are defined in UIColorExtension.swift.
If not, add them, which has been done on 2 occasions
https://jira.catrob.at/browse/CATTY-698

CATTY-698 Unify UI and tint colors

---

src/Catty/PlayerEngine/Instructions/Motion/GlideToBrick+Instruction.swift

CATTY-704: https://jira.catrob.at/browse/CATTY-704
EmbroideryStreams did not work with GlideToBricks because the protocols of the Stitches were never called in the moveAction, now they work as expected.

CATTY-704 GlideToBrick does not work with EmbroideryStreams

---

src/Catty/ViewController/BaseViewController/BaseCollectionViewController.m
src/Catty/ViewController/BaseViewController/BaseTableViewController.m
src/Catty/ViewController/Stage/StagePresenterViewController.m

[CATTY-707](https://jira.catrob.at/browse/CATTY-707)
fixed MenuView (buttons now look good again)
fixed Axis arrows
fixed alignment in landscape mode

CATTY-707 fix landscape mode

---

src/Catty/ViewController/Download/ChartProjects/ChartProjectCell.swift

Fixed the tint of the community accessory indicators
https://jira.catrob.at/browse/CATTY-715

CATTY-715 Fix tint of community accessory indicators

---

src/Catty.xcodeproj/project.pbxproj
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController+MediaLibrary.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController+SelectFile.swift
src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m

Implementation of feature CATTY-717 Allow selection of images from files
Implementation of feature CATTY-717. 
The Implementation is very similar to the Implementation for selecting sound files from the Finder.

CATTY-717 Allow selection of images from files

---

src/Catty/ViewController/Projects/MyProjectsViewController.m

changed color and position of headers
https://jira.catrob.at/browse/CATTY-709

CATTY-709 Fix layout of Project list

---

src/Catty/Defines/UIDefines.swift
src/Catty/ViewController/Stage/StagePresenterViewController.m

CATTY-719 Touch-Events werden durch Achsen im laufenden Spiel blockiert
**Beschreibung:**
Im laufenden Spiel blockieren die Achsen derzeit Touch-Events die direkt auf Höhe der Achsen liegen. 
Dies führt dazu, dass Nutzer keine Interaktionen mit anderen Spielkomponenten durchführen können, wenn diese auf den Achsen liegen und solange die Achsen aktiv sind.
Die Achsen können über das Seitenmenü aktiviert/deaktiviert werden können. (siehe Screenshot)
**Erwartetes Verhalten:**
Die Achsen sollten "transparent" für Touch-Events sein, d.h., selbst wenn die Achsen aktiviert sind, sollten die Nutzer immer noch in der Lage sein, andere Elemente im Projekt zu berühren die dahinter liegen.

CATTY-719 Make stage axis pass through touch events
